- docs/install-pip.rst
- docs/install.rst
- requirements.txt
Fixes #1079 and https://github.com/graphite-project/carbon/issues/348.
> Fix install documentation for pip packages

- LICENSE
- docs/conf.py
> Update copyright to 2015

- LICENSE
- docs/conf.py
> Update copyright to 2015 (0.9.x)

- webapp/graphite/render/functions.py
Constants are not supported.
See issues #626 and #415 that assume not supporting constants is a bug.
> Fixed misleading doc for function diffSeries

- docs/config-carbon.rst
This is a very useful feature and should be better documented. I couldn't find any info about it on Google and ended up having to look into the source code to see what was valid/invalid.
> Add documentation about rewrite-rules.conf

- webapp/graphite/browser/views.py
same XSS fix as merged earlier but now for 0.9.x
> 0.9.x fix XSS issue in user saved graphs

- webapp/graphite/remote_storage.py
> Fix bug introduced in a835a88 (0.9.x)

- webapp/content/js/composer_widgets.js
> fix (some) IE javascript issues

- webapp/graphite/render/functions.py
see discussion here 9da1d8a896ae08deaa36c2c97ea5a5710ae24c0d
> removing useless double call

- docs/who-is-using.rst
Just adding also Outbrain to who uses file
> Adding Outbrain

- .travis.yml
- tox.ini
> Add Django 1.8 to the build matrix

- docs/tools.rst
It's more about monitoring than visualization.
> Move Seyren reference

- docs/render_api.rst
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>
> Doc: fix a typo in render_api.rst

- webapp/graphite/remote_storage.py
The RemoteReader class attempts to reference a connection variable in a dynamic function. This free variable is not valid in Python.
```
Mon Jun 08 03:49:42 2015 :: Error requesting http://graphite:8080/render/?target=STRESS.host.ip-0.com.graphite.stresser.a.%2A&format=pickle&local=1&noCache=1&from=1433731765&until=1433735365
File "/opt/graphite/webapp/graphite/remote_storage.py", line 181, in wait_for_results
response = connection.getresponse()
NameError: free variable 'connection' referenced before assignment in enclosing scope
Mon Jun 08 03:49:42 2015 :: Failed after 2 retry! See: free variable 'connection' referenced before assignment in enclosing scope
File "/opt/graphite/webapp/graphite/render/datalib.py", line …
```
> fix connection in RemoteReader. it cannot be a free variable

- docs/tools.rst
This might be useful as an alternative to Graphite PowerShell Functions <https://github.com/MattHodge/Graphite-PowerShell-Functions>
> New tool (collector): Carbonator Windows Service

- docs/install.rst
Simple formatting for clarity.
> Formatting install.rst

- docs/tools.rst
Brubeck is a statsd-compatible stats aggregator written in C.
http://githubengineering.com/brubeck/
> Add Brubeck to tools list

- webapp/content/js/dashboard.js
Load data for a specific node in a tree when the respective node is expanded.
#1259
> Reset loaded for node to false before expanding node.

- .travis.yml
> Set django-tagging version to 0.3.6 to fix Travis CI for 0.9.x branch

- docs/render_api.rst
Updated render API for minor spelling and grammar updates.
> Minor spelling fix

- webapp/graphite/render/functions.py
Convert asPercent to use matchSeries in order to provide the percentage of list1 to list2..
asPercent(carbon.carbon-daemons.*.cache0.writer.write_operations,carbon.carbon-daemons.*.cache0.writer.datapoints_written)
> Allow asPercent to take two series and match them together

- webapp/graphite/events/views.py
- webapp/tests/test_events.py
> Fix #1028 -- incorrect timezone handling in events

- requirements.txt
- webapp/graphite/render/attime.py
- webapp/tests/test_attime.py
> porting timezone fix to 0.9.x branch

- webapp/graphite/render/glyph.py
Value adapted from the next 2 configs.
> Fix #1305 -- prevent an xAxis config option from being ignored

- webapp/graphite/render/functions.py
Fix for issue https://github.com/graphite-project/graphite-web/issues/1297
> Fixed weighted average to allow its result to be used in other methods

- webapp/graphite/render/datalib.py
> Avoid exceptions when CARBONLINK_HOSTS setting is an empty list.

- webapp/graphite/render/glyph.py
Adds support for hiding the x-axis when rendering graphs, extending the graph to cover the full height
> - add support for hiding the x-axis when drawing graphs

- webapp/graphite/render/glyph.py
without this patch, generating a SVG graph leads to HTTP/500 instead of an red "no data" image like with PNG
> fixed HTTP/500 when generating a SVG graph without any data

- docs/tools.rst
Will add to master branch too.
> Adding bunch of tools - relays, monitoring tools etc.

- docs/tools.rst
Alphabetical resort, capitalize sentences, remove unnecessary wraps.
> Tools page cleanup

- check-dependencies.py
It is already tested on line 72
Follow-up to #1335
> Remove duplicate test import of pytz

- webapp/graphite/render/glyph.py
I suspect the original reason for this has been fixed upstream in cairo. Fixes #1227.
> Stop appending svg closing tag

- check-dependencies.py
- docs/faq.rst
- docs/install.rst
- requirements.txt
Port of #1343 to master. /cc @deniszh
> Remove Twisted dependency (master)

- docs/releases/0_9_13.rst
Cherry-picking this from #1349.
> Update the 0.9.13 release notes

- setup.py
> Attempted fix for RTD builds (0.9.x)

- docs/releases/0_9_13.rst
Please N.B. that I included https://github.com/graphite-project/whisper/pull/136 although it's not merged yet - please remove it from relase notes if it will not merged in release.
> Update of release notes

- docs/releases/0_9_13.rst
Cherry-picking #1358 to master branch.
> Master release notes

- webapp/tests/test_attime.py
- Add tests for parseTimeOffset
- Add tests for getUnitString
Port of #1318 from master to 0.9.x
> Add unit tests for parseTimeOffset in attime class

- webapp/tests/test_attime.py
(Also fix a couple of flake8 violations)
Port of #1276 from master to 0.9.x
> Add unit tests for parseATTime in attime class

- docs/config-database-setup.rst
Missed this one in #1377, spotted by @JeanFred.
> Small typo fix in doc

- docs/config-database-setup.rst
- docs/config-local-settings.rst
- docs/install.rst
Port #1377 to master. /cc @gwaldo
> Database setup doc

- docs/tools.rst
Adding influx is not _just_ a :trollface: for @obfuscurity
> adding 'alternate storage backends' section to the tools doc

- webapp/graphite/render/functions.py
See issue #1374. Currently, because ``timeShift`` offsets time by a fixed number of seconds, comparing a time period with DST to a time period without DST, and vice-versa, results in an apparent misalignment. For example, 8am might be overlaid with 7am. To compensate for this, I added the ``alignDST`` option to the ``timeShift`` function. This option is disabled by default. 
``alignDST`` is basically a shortcut for adding +/- 1 hour to the time shift. It only takes affect if the from and until times were both in DST, and the timeShift-ed time was outside DST (and vice-versa).
> Added timeShift option to compensate for DST

- conf/graphite.wsgi.example
> Fixing WSGI example config

- webapp/graphite/render/functions.py
> Continue on IndexError for removeAbovePercentile and removeBelowPercentile (0.9.x)

- docs/render_api.rst
hideXAxis was merged in #1239, unfortunately I missed the documentation for it so here it is
> - add missing documentation for hideXAxis to render api

- webapp/graphite/render/evaluator.py
- webapp/graphite/render/functions.py
- webapp/graphite/render/glyph.py
Just some spelling corrections in docs/message strings.
> Spelling corrections.

- docs/tools.rst
Cleanup and simplify, fix order, etc.
> Minor tweaks for jmx2graphite tools entry

- webapp/graphite/render/functions.py
Backport https://github.com/graphite-project/graphite-web/pull/1364 to 0.9.x. My gift to you this Black Friday.
> Add natural sorting to sortByName (0.9.x)

- docs/releases/0_9_15.rst
> Release notes correction (0.9.x)

- docs/releases/0_9_15.rst
> Release notes correction

- docs/conf.py
- tox.ini
Reverts graphite-project/graphite-web#1429
@brutasse see https://readthedocs.org/projects/graphite/builds/3546170/
> Revert "Fix docs build with Django 1.9"

- docs/tools.rst
This is new monitoring tool based on graphite data.
> Add Moira monitoring link

- docs/who-is-using.rst
GOV.UK uses graphite extensively. I work on the GOV.UK Infrastructure Team.
> Add GOV.UK to list of users

- docs/who-is-using.rst
Mackerel uses graphite quite heavily. I am a member of the Mackerel operation engineers.
> Add Mackerel to list of users

- docs/config-local-settings.rst
> Update config-local-setting.rst. Line 87

- README.md
- docs/config-local-settings.rst
- docs/development.rst
- docs/tools.rst
- misc/virtualenvwrapper/postactivate
- misc/virtualenvwrapper/postdeactivate
- setup.py
- webapp/graphite/local_settings.py.example
- webapp/graphite/settings.py
> changing references to readthedocs.org to .io

- docs/render_api.rst
- webapp/graphite/render/glyph.py
- webapp/graphite/render/views.py
Added the ability to render PDFs with the render API. There should be no additional requirements beyond what is already required.
> Add ability to render PDFs

- webapp/content/js/dashboard.js
Correct function call to be the correct one.
> Graphs -> New Graph -> From Metric has the wrong function called when pressing enter on the input box

- webapp/tests/test_util.py
Just a couple small test cases.
> Add coverage to util.py for IPv6 and write_index

- webapp/graphite/metrics/views.py
- webapp/tests/test_metrics.py
I am attempting to understand how to create test cases in Graphite.  This adds coverage to graphite.metrics.
> Add test coverage to /metrics/

- webapp/graphite/dashboard/views.py
- webapp/tests/test_dashboard.py
Add more test coverage to graphite/dashboard/
Fix bug in email routine
Fix bug in loading a template directly from URL
Fix two bugs in template save and delete.
> Add more test coverage to graphite/dashboard

- webapp/tests/test_util.py
Adding a few more tests.  I think I have one spot left I can easily add another check for util.py.  I'll verify with codecov.io output.
> More coverage to util.py

- webapp/graphite/dashboard/views.py
- webapp/tests/__init__.py
- webapp/tests/conf/dashboard.conf
- webapp/tests/conf/dashboard.conf.invalid_theme
- webapp/tests/conf/dashboard.conf.missing_keyboard-shortcuts
- webapp/tests/conf/dashboard.conf.missing_ui
- webapp/tests/test_dashboard.py
Correct a bug in template if the dashboard-\<theme>.css does not exist.
Cover almost all cases with graphite/dashboard.
> Add more coverage to dashboard

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/graphite/render/functions_test.py
This cherry-picks PR 358 (originally from mattus/sortbytotal to master)
ec53455 add sortByTotal function
08e6e69 test for sortByTotal
> Cherry-pick pull request #358 from master

- webapp/graphite/settings.py
- webapp/tests/settings.py
* Define a few variables before first use within conditionals.
* Remove extraneous define of CLUSTER_SERVERS
* Correct usage of join in test/test_settings.py
> Fix new errors from newer pyflakes

- setup.py
> Adding trove classifiers.

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
* Add input chekcs to safePow and safeStdDev
* Fix safeMap to work safely
* Add tests for safeSum()
* Add tests for safeDiff()
* Add tests for safeLen()
* Add tests for safeDiv()
* Add tests for safePow()
* Add tests for safeMul()
* Add tests for safeSubtract()
* Add tests for safeAvg()
* Add tests for safeStdDev()
* Add tests for safeLast()
* Add tests for safeMin()
* Add tests for safeMax()
* Add tests for safeAbs()
* Add tests for safeMap()
* Add tests for gcd()
* Add tests for lcm()
* Add/expand tests of normalize()
* Add tests for matchSeries()
* Add tests for formatPathExpressions()
* Add tests for sumSeries()
* Add tests for sumerSeriesWithWildcards()
* Add tests for averageSeriesWithWildcards()
* Add tests for diffSeries()
* Add tests for averageSeries()
> Add coverage for helper functions

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
* Adjust keepLastValue() to be inclusive of the limit value of None values at the end of series.
* Add test for stddevSeries()
* Add test for minSeries()
* Add test for maxSeries()
* Add test for rangeOfSeries()
* Add test for percentileOfSeries()
* Expand tests for _getPercentile()
* Add tests for keepLastValue()
* Add tests for asPercent()
* Add tests for divideSeries()
* Add tests for multiplySeries()
> Add additional tests

- webapp/tests/test_render.py
Tests for ConsistentHashRing Class
> Add test coverage for ConsistentHashRing

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
Proposed fixes for #1557
* When total is not passed, set totalText = "sumSeries(%s)" % formatPathExpressions(seriesList)
* Rename seriesList2orNumber to total.
* Remove extra space in pathExpression
> Changes to asPercent for issue #1557

- docs/carbon-daemons.rst
refs https://github.com/graphite-project/graphite-project.github.io/issues/12
> Missing bits from wikidot carbon page

- docs/carbon-daemons.rst
refs https://github.com/graphite-project/graphite-project.github.io/issues/12
> Missing bits from wikidot carbon page (0.9.x)

- docs/events.rst
- docs/index.rst
> Add events page

- docs/events.rst
- docs/index.rst
refs https://github.com/graphite-project/graphite-project.github.io/issues/10
> Add events page (0.9.x)

- webapp/tests/test_attime.py
Tests show no issues when the current date is on or around Feb 29th in Master.
> Add tests to attime for when current date is Feb 29th.

- docs/config-database-setup.rst
- requirements.txt
Pin Graphite to Django 1.9 and django-tagging 0.4.3. Update the install docs accordingly.
Fixes #1573.
Refs #1555 #1425
> Pin master to Django 1.9

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
* Change doc string to be correct
* Add test for cumulative()
* Add test for consolidateBy()
> Cumulative() function has incorrect doc string

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
* Add coverage for weightedAverage()
* Change weightedAverage() to have deterministic pathExpression generation
* Add tests for weightedAverage()
* Add tests for scaleToSeconds()
* Add test for absolute()
* Add test for offset()
* Add test for offsetToZero()
* Add test for derivative()
* Add test for nonNegativeDerivative()
* Add test for perSecond()
> Add more tests for functions

- webapp/graphite/local_settings.py.example
Some minor housekeeping of `local_settings.py.example` comments and ordering to improve readability.
> Housekeeping of local_settings.py.example

- webapp/graphite/remote_storage.py
* Don't suppress exceptions in remote_storage.FindRequest
> Fix issue #1454

- webapp/tests/test_functions.py
* Remove extraneous assertEqual from weightedAverage and scaleToSeconds tests
* Add tests for stacked()
* Add tests for areaBetween()
* Add tests for cactiStyle()
* Add tests for aliasByMetric()
* Flush out tests for legendValue()
* Add tests for substr()
> Add more test coverage to render/functions.py

- webapp/graphite/settings.py
- webapp/graphite/storage.py
This is a backport of #360 to the 0.9.x branch.
> Make the rrdtool CF configurable in 0.9.x

- docs/render_api.rst
> Undocumented pie chart parameters

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
Change name in transformNull when a referenceSeries is passed in.
* Change nPercentile() test to be more correct.
* Add tests for averageOutsidePercentile()
* Add tests for removeBetweenPercentile()
* Add tests for sortByName()
* Add tests for sortByMaxima()
* Add tests for sortByMinima()
* Add tests for transform_null() with Reference Series passwed in
* Add tests for isNonNull()
* Add tests for identity()
* Add tests for aggregateLine()
* Add tests for threshold()
> Add more coverage for render functions

- webapp/tests/test_functions.py
* Add tests for countSeries()
* Add tests for group()
* Add tests for exclude()
* Add tests for grep()
* Expand test for applyByNode to not pass newName
* Add tests for smartSummarize()
* Add tests for hitcount()
* Add test for summarize()
> Add more render/function.py tests

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
This supersedes #1507, bringing in @ckolbeck's enhancement and adding a test suggested by @cbowman0.
> Have countSeries return zeroes instead of empty series

- docs/render_api.rst
- webapp/graphite/render/views.py
- webapp/tests/test_render.py
This PR supersedes #1119, fixing some bugs and adding documentation for the new format types. Tested on my local Synthesize/master system.
> Dygraph and Rickshaw format types

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
This supersedes #1301, fixing some merge conflicts and improving the documentation.
/cc @Blackbaud-JesseHodges since he wrote the initial implementation, @pvanassen who introduced the proposed change, and @cbowman0 who added the recent set sorting behavior.
> Weighted average multi node

- webapp/graphite/readers.py
Introduced in https://github.com/graphite-project/graphite-web/pull/710.
> Flake8 whitespace fix

- docs/who-is-using.rst
This supersedes #659, submitted by @dgutzeit. Cleaned up a merge conflict and reordered one.
> Add Maaii to "who is using" page

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
This PR supersedes #1137, introducing a new series-level `interpolate()` function by @landlord11. I finished the change by exposing it to the render evaluator and adding it to the Composer widget UI.
> Interpolate function for series

- tox.ini
> Pin flake8 to 2.6.2 until we can make 3.x work

- webapp/tests/test_functions.py
> Add test for interpolate function

- webapp/graphite/render/views.py
- webapp/tests/test_render.py
This includes the commits from @heliodor from #748 along with some test cases format=raw and large floats.
> Expand format=raw output to include more float digits

- webapp/graphite/events/models.py
- webapp/graphite/events/views.py
- webapp/tests/test_events.py
This PR supersedes #636, merging conflicts and fixes #635.
/cc @brutasse @cbowman0
> Event tags creation and serialization

- webapp/graphite/local_settings.py.example
- webapp/graphite/render/glyph.py
- webapp/graphite/settings.py
This PR supersedes #461, resolving merge conflicts.
refs #188
> Configurable DATE_FORMAT

- webapp/graphite/render/glyph.py
Accidentally reverted c47acb6 in my merge conflict resolution for #1633. Spotted by @iain-buclaw-sociomantic.
> Restore xAxisConfig change

- webapp/content/js/completer.js
- webapp/graphite/finders/standard.py
- webapp/tests/test_finders.py
Changes from @mark-5 from #1178 
* Manually merge into finders/standard.py.
* Adjust the test cases.
> Add support for globstars in standard finder

- .travis.yml
- webapp/graphite/render/functions.py
From #505, porting this over to 0.9.x. Fixes #1646.
> Port timeShift fix to 0.9.x

- webapp/content/js/browser.js
- webapp/graphite/templates/composer.html
This PR supersedes #431, resolving conflicts and squashing one minor bug. Fixes #723.
> Add a refresh button to Metrics tree

- docs/config-carbon.rst
Update aggregation-rules.conf documentation with examples from aggregation-rules.conf.example
> Update aggregation-rules.conf documentation

- webapp/graphite/browser/views.py
This PR supersedes #1470. Thanks to @Sinkmanu for finding this and submitting the initial patch. I've reworked it a bit so that it handles multiple `target` params.
> Sanitize graph urls for XSS

- webapp/graphite/readers.py
- webapp/graphite/remote_storage.py
See https://github.com/graphite-project/graphite-web/issues/1617
This restore previous performances when REMOTE_STORE_MERGE_RESULTS is enabled
> Remote merge performance fixes

- webapp/graphite/storage.py
Fixing issue #1670 
Local merging also works.
> Fixing local queries regression when REMOTE_STORE_MERGE_RESULTS enabled

- docs/tools.rst
Mentioned by @strajansebastian in #1685, fixed here.
> Add Icinga 2 to tools page

- webapp/graphite/render/functions.py
> Copy tzinfo when modifying startTime in smartSummarize()

- setup.py
Matches the versions in `requirements.txt`.
> Specify install_requires versions

- webapp/graphite/metrics/views.py
> Read RRD files for index.json

- webapp/graphite/render/functions.py
> Fix docstring rst syntax

- webapp/graphite/render/functions.py
Documentation of `total` parameter changed to match the expected input type/format
> Updates documentation of asPercent()

- webapp/graphite/render/views.py
> Log render times for json

- webapp/graphite/composer/views.py
- webapp/graphite/remote_storage.py
- webapp/graphite/render/views.py
Noticed that 0.9.x has some of this thanks to #1330. Porting it over to master.
refs #1690
> Use HTTP buffering if available

- webapp/graphite/storage.py
* Expand braces based on https://bugs.python.org/issue9584
Allow multiple braces (both serial and nested) to be expanded
> Fix brace expansion

- webapp/graphite/readers.py
trivial fix for a symlinked file issue
> return realpath to fix issues with symlinks

- webapp/graphite/local_settings.py.example
Discovered by @ybizeul, refs #1728.
> Remove accidental special character

- webapp/graphite/storage.py
Backport of https://github.com/graphite-project/graphite-web/pull/1730 to 0.9.x
> Optimizing brace expansion (in 0.9.x)

- webapp/graphite/readers.py
- webapp/tests/test_readers.py
This fixes #1701 
* Expand the merge_with_cache to consolidate data using the aggregation method passed in.
* Always issue carbonlink request for WhisperReader
> Fixes for issue #1701

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
- fix the aliasByMetric impl
- add unit tests on aliasByMetric
> aliasByMetric() display a trailing ')'

- docs/events.rst
I noticed there were a few problems with the event documentation, so I updated it to be more complete/correct.
> fixes event documentation

- docs/events.rst
> Minor tweak to events doc

- docs/ceres.rst
- docs/config-local-settings.rst
- docs/index.rst
- docs/install.rst
- webapp/graphite/readers.py
- webapp/graphite/settings.py
Based on existing documentation, some parts from `whisper.rst` where similarities crossed.  And some general experience.
What's immediately missing are:
Initially putting this here so a proper review can be done, spelling, etc.
> Ceres: Add detailed documentation

- docs/releases/0_10_0.rst
De-emphasize Ceres for now but let's add a link to the new doc.
> Minor change to 0.10.0 release notes

- webapp/graphite/render/functions.py
- Adds check for None before integer comparisons.
- Converts list comprehension code into loop.
- Add tests for averageAbove/Below()
- Add tests for currentAbove/Below()
- Add tests for maximumAbove/Below()
- Add tests for minimumAbove/Below()
N.B: These functions only fail when using Python 3, not 2.7.
> average/current/max/min Above/Below fails if there is no data.

- bin/run-graphite-devel-server.py
for https://github.com/graphite-project/graphite-web/pull/622
@iksaif please review this pr!
> Implementation called django-admin.py

- docs/config-local-settings.rst
per this doc where its set as such.
https://github.com/graphite-project/graphite-web/blob/master/docs/config-database-setup.rst
> Update the command to setup a new database.

- docs/tools.rst
Hi,
Not sure if this the correct workflow for proposing to add a tool to this list, but I'll give it a go :-) It would be great for my project to be on the list, if you have any questions, please let me know!
Cheers Daniel
> Added Targets-io to tools list

- requirements.txt
- setup.py
Looks like it works well with the latest version (and the old
one is problematic now)
> requirements: unpin pyparsing

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
> Introduce a movingSum() function

- setup.py
Fixes #1806 
Tested and confirmed.
> Pin Pyparsing to < 2.1

- webapp/graphite/render/functions.py
My PR from yesterday (#1808) doesn't work, I'm afraid. The missing piece is here.
> Make movingSum available for use

- webapp/graphite/remote_storage.py
The structure of the pickled response from the find endpoints changed from 0.9.x to master, this patch allows a front-end instance running master to use back-end nodes running 0.9.x by accepting both result formats.
> support 0.9.x backends

- webapp/graphite/events/views.py
- webapp/graphite/render/views.py
They didn't work because of this: https://docs.djangoproject.com/en/1.10/releases/1.7/#merging-of-post-and-get-arguments-into-wsgirequest-request
> Change remaining deprecated request.REQUEST

- webapp/graphite/render/functions.py
The difference in semantics is important, so clarify.
> perSecond is nonNegativeDeriviative, not Derivative

- .gitignore
- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
- webapp/tests/test_metrics.py
Reverts graphite-project/graphite-web#1792
Because of flacky tests
> Revert "Exponential Moving Average Function Implementation"

- docs/tools.rst
No longer maintain Graphite-Observer, remove it, thx.
> No longer maintain Graphite-Observer

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
Add movingMin and movingMax functions
We use these functions in alerting system to avoid trigger flapping. I think it could be useful for others.
> Add movingMin and movingMax functions

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
I needed it to analyze `input - output` chain of my services.
Example
| IN | OUT | OUT^IN | Conclusion |
| --- | --- | --- | --- |
| 1 | 1 | 1 | OK |
| 0 | 0 | 1 | OK |
| 2 | 0 | 0 | BAD |
| 3 | 2 | 8 | OK |
At the end I have graph like this
Before 12 you can see that something was comming, but noting was going out, but later on at 12 something got fixed and data went out off the chain.
We are using it for alerting.
> powSeries function

- docs/install.rst
also mentioning that taggit is not supported yet.
Fixing #1871
> Including scandir as dependency

- docs/install-pip.rst
> Fixing pip install docs

- docs/install-pip.rst
> Fixing pip install docs for 0.9.x

- setup.py
This pull request contains what we need to merge back into master.
> 1.0.x -> master

- webapp/graphite/readers.py
> Trying to catch IOerror around whisper.fetch

- webapp/graphite/local_settings.py.example
- webapp/graphite/settings.py
> settings: reduce default number of threads

- webapp/graphite/carbonlink.py
- webapp/graphite/readers.py
- webapp/graphite/singleton.py
- webapp/tests/test_singleton.py
Also make readers.py pull less dependency and add
graphite.singleton to make it easier to have singleton.
This could also be used for some of our other singletons
to allow easier lazy-initialization.
See #1014 , #1886
> carbonlink: make it easilly importable, delay initialization

- docs/releases.rst
- docs/releases/0_9_16.rst
- docs/releases/1_0_0.rst
- Adding release 0.9.16 docs
- Fixing release notes of 1.0.0
- pin 0.9.16 in pip
- Remove Ceres, add Whisper changes and fixes
- Typo
- Adding release date
> Cherry pick release docs (#1879) to master

- docs/releases.rst
- docs/releases/0_9_16.rst
- docs/releases/1_0_0.rst
* Adding release 0.9.16 docs
* Fixing release notes of 1.0.0
* pin 0.9.16 in pip
* Remove Ceres, add Whisper changes and fixes
* Typo
* Adding release date
> Release docs (#1879)

- docs/releases.rst
- docs/releases/1_0_1.rst
Backport doc changes  to master
> Release 1.0.1

- setup.py
> Fix scandir dependency

- webapp/graphite/settings.py
> Change WEBAPP version for master branch

- webapp/graphite/render/functions.py
> Typo in annotation

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
Iterates over a two lists and divides list1[0] by list2[0], list1[1] by list2[1] and so on.
> divideSeriesLists function

- webapp/content/css/dashboard.css
- webapp/content/js/dashboard.js
Since PR #1845, there is no feedback on image refreshes.  This change gives feedback.  I can't claim this is the cleanest or best way to do it, so if someone has better ideas and/or methods please let me know.
> Dashboard image refresh feedback

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
Hello,
Following my feature request #1936, I had a look to the code and it appeared not so difficult to implement it by myself.
Here is the result.
I hope someone else may find this useful.
Code has been tested in production.
> Issue #1936 - aliasQuery function

- docs/carbon-daemons.rst
See https://github.com/graphite-project/carbon/pull/659 for the code
> Add carbon-aggregator-cache documentation

- webapp/graphite/settings.py
Backport of #1962 from master branch
> Fix LDAP auth in 1.0.x

- setup.py
- tox.ini
- capping Django to <1.11.99 in setup.py
- same for tox.ini but for different versions
> Fix django versions

- .travis.yml
- check-dependencies.py
- requirements.txt
- setup.py
- tox.ini
Add Django 1.8 to the tests and other relevant sections.
As discussion in issue #1967.
> Django 1.8

- .travis.yml
- check-dependencies.py
- requirements.txt
- setup.py
- tox.ini
> Django18 testing for 1.0.x

- webapp/content/css/dashboard.css
- webapp/content/js/dashboard.js
Cherry-pick of #1933 for 1.0.x
> Dashboard image refresh feedback for 1.0.x branch

- webapp/graphite/render/views.py
> Pie charts with remote prefetch

- webapp/graphite/dashboard/views.py
> Dashboard finder improvements for 1.0.x

- docs/install.rst
Adding Docker info snippet to install doc for master
> Adding small docker info to install docs

- webapp/graphite/finders/remote.py
> fix divideByZero when FIND_CACHE_DURATION=0

- webapp/graphite/render/hashing.py
- webapp/tests/test_render.py
replicates https://github.com/graphite-project/carbon/pull/679
> compute_ring_position - invalid literal error

- webapp/graphite/render/functions.py
This improves the internal efficiency of the summarize and smartSummarize functions to help improve the performance issue discussed in #1915 
As far as I can tell it should be logically identical to the existing code, but I'd appreciate any feedback.
> improve efficiency of summarize and smartSummarize functions

- webapp/content/js/composer_widgets.js
- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
This follows on from #1780, and implements a solution for #1779 
I changed the name of the function to `unique()` as discussed in #1780, and also fixed up a couple of literal tabs that snuck into `composer_widgets.js`
> Implement unique()

- webapp/tests/test_functions.py
Tests for timeStack, useSeriesAbove, fallbackSeries, mostDeviant and stdev.
> Add more test coverage for functions

- webapp/tests/test_render_datalib.py
Add basic tests for _merge_results from render/datalib.
> Basic tests for render/datalib's _merge_results()

- webapp/tests/test_render_datalib.py
Add tests for the render/datalib's PrefetchData class.
> Test class PrefetchedData

- webapp/tests/test_render_datalib.py
Add more _FetchData tests
Add basic prefetchRemoteData
> Add more tests for render/datalib.py

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
This closes issue with empty series which leads to unwanted exceptions when using this function.
> Added check for empty series list on percentileOfSeries

- webapp/content/js/dashboard.js
This field should NOT be urlencoded.  Oops.
> Fix PR #2087

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
Currently the series returned by `seriesByTag` have `pathExpression` set to `group(<list of matching series>`, which can be very long and unwieldy.  This PR changes the behavior so that `pathExpression` on the returned series are set to match the `seriesByTag` call, as suggested by @shanson7.
It also includes an update to `getNodeOrTag` to save some work when using tags, and to properly return the last node in the name of a tagged series (currently it would include all the tags).
Finally, I fixed a typo where the `absolute()` function adds the wrong tag.
> set pathExpression on seriesByTag results

- webapp/graphite/storage.py
> use default tagdb if TAGDB setting is not set.

- webapp/graphite/logger.py
Right now there isn't an esasy way to enable debug logging, this PR sets the log level to debug when settings.DEBUG is True.
> set log level to debug when settings.DEBUG is True

- webapp/graphite/render/functions.py
- webapp/graphite/render/glyph.py
Removed a duplicate threshold key in the SeriesFunctions dict.
Remove a few unused variables.
> Clean up a few codacy issues

- requirements.txt
Version 0.8 adds Python 3 support
> Bump pinned txAMQP version

- webapp/content/js/browser.js
- webapp/content/js/completer.js
- webapp/content/js/composer.js
- webapp/content/js/composer_widgets.js
- webapp/content/js/dashboard.js
Change made via `eslint --no-eslintrc --rule 'quotes:[error,"single"]' --fix`
> Convert to single quotes since that is predominant.

- webapp/content/js/browser.js
- webapp/content/js/dashboard.js
Make the variables camel case where possible.
> Convert javascript variables to camelCase to match predominant standard.

- docs/storage-backends.rst
This PR outlines the additional methods that can be implemented by advanced finders.
> Advanced finder docs

- bin/run-graphite-devel-server.py
- check-dependencies.py
- contrib/demo-collector.py
- contrib/memcache_whisper.py
- contrib/test_aggregator_rules.py
- examples/example-client.py
Made devel server py3 compatible and fixed some other print statements while at it.
> minor Python 3 fixes

- docs/functions.rst
- docs/install.rst
- docs/releases.rst
- docs/releases/1_1_0.rst
- docs/storage-backends.rst
- docs/tags.rst
- webapp/graphite/settings.py
Please review. Will proofread that, but I'm not a native English speaker, so, please fix (or notify me about) errors and/or odd phrasing.
> Release Notes for 1.1.0 release

- webapp/graphite/render/functions.py
This PR fixes up a few formatting issues in the function docstrings.
> Tweak function docs

- webapp/graphite/render/functions.py
> [1.1.x] tweak function docs

- webapp/graphite/render/hashing.py
- webapp/tests/test_render.py
See https://github.com/graphite-project/carbon/pull/726
> hashing: better performances

- webapp/graphite/render/datalib.py
> Do not try merge series with different length

- docs/admin-webapp.rst
- docs/config-local-settings.rst
- docs/config-webapp.rst
- webapp/graphite/app_settings.py
- webapp/graphite/finders/remote.py
- webapp/graphite/local_settings.py.example
- webapp/graphite/readers/remote.py
- webapp/graphite/render/datalib.py
- webapp/graphite/render/hashing.py
- webapp/graphite/settings.py
- webapp/graphite/storage.py
- webapp/graphite/tags/http.py
- webapp/tests/test_finders_remote.py
- webapp/tests/test_readers_remote.py
- webapp/tests/test_render.py
- webapp/tests/test_storage.py
[] Do not try merge series with different length
[] rename timeout settings
[] hashing: use a generator instead of looking for all targets
[] hashing: sync with carbon
[] hashing: better performances
[] app_settings: append() doesn't work on tuples
[] remove useless links in webapp config stack list
[] fix webapp config list
[] add doc for setup and deploy with nginx+gunicorn stack
> Backport more commits to 1.1.x

- docs/config-webapp.rst
- docs/tools.rst
- some changes for tools and config-web pages in the documentation.
> Documentation fixes

- docs/config-webapp.rst
- docs/tools.rst
- Some changes to the "tools" page (#2200)
- Extending web config page (#2201)
- Adding cassabon (#2201)
> [1.1.x] Some changes to the "tools" page | Extending web config page | Adding cassabon

- docs/tools.rst
- webapp/graphite/readers/whisper.py
Should fix https://github.com/graphite-project/graphite-web/issues/196
Please check https://github.com/graphite-project/graphite-web/issues/196#issuecomment-357964575 for details
> Propagate `now` parameter for whisper reader

- docs/tools.rst
Missed this commit from docs PR somehow
> Adding Graphouse to the Tools page

- docs/config-carbon.rst
Documentation for https://github.com/graphite-project/carbon/pull/696.
> Percentile aggregation documentation

- webapp/graphite/render/functions.py
- webapp/tests/test_functions.py
- Add seasonality parameter for holt-winters functions (#2225)
- fix indent (#2225)
- functions: fix holtWinterAberration with multiple targets (#2226)
> [1.1.x] Add seasonality parameter for holt-winters functions | fix indent | functions: fix holtWinterAberration with multiple targets

- docs/releases.rst
- docs/releases/1_1_2.rst
> [1.1.x] Release docs

- webapp/graphite/render/functions.py
> fix hitcount bucket calculation

- docs/config-webapp.rst
here I present my doc fix! Thanks!
> fixed missing static location in nginx + uwsgi conf #2260

- docs/config-webapp.rst
> Fixing typo in docs

- webapp/graphite/render/hashing.py
see https://github.com/graphite-project/carbon/pull/778
> hashing: bisect fix for py3

- webapp/graphite/metrics/views.py
Fixing https://github.com/graphite-project/graphite-web/issues/2292
> Generate error when find query is empty

- webapp/graphite/render/datalib.py
- webapp/graphite/render/hashing.py
Needed for python 3.7 compatibility
> replace raise StopIteration with return pep-0479

- docs/feeding-carbon.rst
https://github.com/graphite-project/graphite-web/issues/2308
> Document timestamp -1 in carbon protocol

- webapp/graphite/render/datalib.py
One way to address the issue I opened last week: https://github.com/graphite-project/graphite-web/issues/2318
> convert prefetched values generator to reusable iterator

- docs/config-carbon.rst
Resolves https://github.com/graphite-project/carbon/issues/620
> add doc note about equal sign in rewrite rule's pattern

- webapp/graphite/finders/standard.py
- webapp/tests/test_finders.py
Fixes graphite-project/graphite-web#2369
> Fix carbonlink queries for tagged series.

- docs/config-carbon.rst
fixes: https://github.com/graphite-project/carbon/issues/821
> docs: add link to regex documentation

- .travis.yml
- tox.ini
- webapp/graphite/readers/rrd.py
- webapp/tests/test_readers_rrd.py
Fix from https://github.com/graphite-project/graphite-web/pull/2377 and added tests.
> RRD path fix and tests

- webapp/tests/test_composer.py
Basic test I had sitting in a branch for a bit so I made it work.
> Add coverage for composer's send_email function

- MANIFEST.in
- setup.py
Resolves https://github.com/graphite-project/graphite-web/issues/2404
> set package long description

- webapp/graphite/render/functions.py
there is probably a bunch of other places where the same update needs to happen.
actually, probably better to just document them all in 1 place and then link to them.
but i'm not sure how to best do that
> update aggregation function docs for aggregate and groupbytags

- docs/tools.rst
More information about Statusengine and Tutorial about how to setup: https://statusengine.org/tutorials/Graphite-Grafana/
> Add Statusengine to list of integrations (Forwarding)

- webapp/graphite/errors.py
- webapp/graphite/functions/params.py
- webapp/graphite/render/evaluator.py
- webapp/graphite/render/functions.py
- webapp/graphite/render/views.py
- webapp/graphite/settings.py
- webapp/tests/test_params.py
There are many cases where bad user input leads to a 5xx error. We want to handle those better and return 400 when it's appropriate
> Fix 5xx on bad request

- webapp/graphite/render/views.py
PR for #2478 
Adds maxDataPoints to the requestContext
> Pass maxDataPoints to the requestContext for Finder

- webapp/graphite/render/functions.py
Issue #2355 suggests that minimumBelow() works on <= rather than <, to avoid confusion I have updated docstring
> Updated minimumBelow() docstring #2355

- webapp/graphite/render/datalib.py
prefetchData may be called multiple times in one request, so prefetched data must be merged.
> Merge prefetched data

- .travis.yml
- tox.ini
Python 2 is eol, we can test docs on Python 3
> test docs on Python3

- bin/run-graphite-devel-server.py
- check-dependencies.py
- docs/conf.py
- examples/example-client.py
- setup.cfg
- setup.py
- tox.ini
- webapp/graphite/account/ldapBackend.py
- webapp/graphite/dashboard/views.py
- webapp/graphite/logger.py
- webapp/graphite/render/functions.py
- webapp/graphite/render/glyph.py
- webapp/graphite/settings.py
- webapp/tests/test_functions.py
- webapp/tests/test_readers_util.py
re-enable some flake8 rules which cause the least code churn
> prune flake8 ignore list

- contrib/demo-collector.py
- contrib/memcache_whisper.py
- contrib/test_aggregator_rules.py
- setup.cfg
- webapp/graphite/util.py
- webapp/tests/test_functions.py
another small chunk of flake8 "compliance" work
> flake8: include contrib/ subdir, re-enable rule E713

- webapp/graphite/functions/params.py
@DanCech is that like what you had in mind in your recent comment?
> move all validation into Param.validateValue

- CHANGELOG.md
- CONTRIBUTING_FOR_COMMITTERS.md
I hope it will help us with tracking changes and doing releases more often
> Adding global changelog

- webapp/graphite/render/glyph.py
fixes graphite-project/graphite-web#2518
> Fix SVG output for Python3

- bin/run-graphite-devel-server.py
- webapp/graphite/render/views.py
- webapp/graphite/util.py
see https://github.com/graphite-project/graphite-web/pull/2581
> Remote render fixes

- webapp/graphite/finders/__init__.py
- webapp/tests/test_finders.py
see https://github.com/graphite-project/graphite-web/pull/2326
> Revert symlink

- docs/tools.rst
Relates to https://github.com/tomkerkhove/promitor/issues/938
> List Promitor as a collector tool

- webapp/graphite/render/functions.py
> Proper groups for isNonNull() and powSeries()

- .deepsource.toml
- .github/workflows/tests.yml
Keeping Travis for now, tests on GHA sometimes flacky (well, because they're flacky in general...)
> 1.1.x: Adding tests, disabling deepsource

- webapp/content/js/dashboard.js
Backporting missing commit to 1.1.x, fixing  #2711
> html-encode text passed to Ext.Msg

- webapp/graphite/render/functions.py
> Fix issue with too small season length (#2780)

- docs/terminology.rst
- [Introduce the term "node" (#2793)](https://github.com/graphite-project/graphite-web/pull/2793)
> [1.1.x] Introduce the term "node" (#2793)

- .github/workflows/tests.yml
- .readthedocs.yaml
- docs/requirements.txt
- requirements.txt
- tox.ini
Did some housekeeping:
- added readthedocs config
- fixed tests
- relaxed Django version (<5 looks like works, but more testing is needed)
> Adding readthedocs config

- webapp/graphite/events/models.py
- webapp/tests/test_events.py
Last attempt to keep events in the code for Django 4.2
> Monkeypatching tagging
