graphite-project/graphite-web

docs/install-synthesize.rst

Remove Synthesize bits which may be misinterpreted. Mention that it only supports `0.9.13`. And point to the official project docs.

Fix Synthesize install doc

---

docs/install-synthesize.rst

Remove Synthesize bits which may be misinterpreted. Mention that it only supports `0.9.13`. And point to the official project docs.

Fix Synthesize install doc (0.9.x)

---

docs/releases/0_9_11.rst
docs/releases/0_9_9.rst

This should fix warnings I've seen in the RTD build:
```
/var/build/user_builds/graphite/checkouts/0.9.13-pre1/docs/releases/0_9_11.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/build/user_builds/graphite/checkouts/0.9.13-pre1/docs/releases/0_9_11.rst:115: WARNING: Title underline too short.
/var/build/user_builds/graphite/checkouts/0.9.x/docs/releases/0_9_9.rst:44: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

Fix doc indentation and title underline warnings (0.9.x)

---

webapp/graphite/render/functions.py

Remove this, otherwise it ends up getting built for the RTD docs.

Bad multiline comment in functions.py

---

webapp/graphite/render/functions.py

Backport of #1107 against 0.9.x

Fixed misleading doc for function diffSeries

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This change will allow selecting only a slice of time from a line to display on the graph. This is useful in the following situation:
A customer just wants to know how much bandwidth their site used last year. They don't care about the link to their site. At the beginning of the year the customer is using port ge-0/0/0. Halfway through the year the customer is upgraded to ae0, an aggregated port that contains ge-0/0/0. All traffic that goes through ae0 necessarily goes through ge-0/0/0. Were a graph to be made over the entire year for all traffic to the site then it would have to include both ge-0/0/0 and ae0 to cover the whole year except that from 'Jul 1' to 'Dec 31' would be double the actual value because it would include traffic from both ge-0/0/0 and ae0. This new function, combined …

adding timeslice method

---

webapp/graphite/browser/views.py
webapp/tests/test_browser.py

Calling `str()` on unicode strings makes python 2 unhappy…

Fix graph lookup with non-ascii names

---

webapp/graphite/browser/views.py

Fixes XSS vulnerability when saving a graph.
When logged, click in a graph to save to my graphs, then enter html/js code. When exanding the User Graph tree this code will get executed.

fix XSS issue in user saved graphs

---

webapp/graphite/render/glyph.py

yMin was set to 0.0 for series containing at less one null value, even
if it contains negative values, hence hiding those values
yMax was not set to 0.0, even if series contains nulls and its maximum
non-null value is < 0.0
Fixes issue #1105

Fixed automatic computing of yMin and yMax when drawNullAsZero=true

---

webapp/graphite/settings.py

This is *not* a formal release or tagging, just noticed this version set in settings.py so let's go ahead and bump it.

Bump webapp version to 0.9.13

---

docs/tools.rst

I wrote tool to export\import\copy\sync graphite dashboard (https://github.com/blacked/graphite-dashboard).
It allow to track dashboards in git, and because it keep dashboards as YAML files it also easy to modify them.
I suppose it will be useful to refer to it in Graphite dashboards documentation.

Add graphite-dashboard to tools.rst

---

bin/run-graphite-devel-server.py

Defaults to 0.0.0.0, so existing behavior remains unchanged. But it's easier when running a dev instance on a laptop and not wanting to mess around with OS X firewall setting, to just specify --interface=127.0.0.1 instead.

Add --interface flag, to allow devel server to only listen on 127.0.0.1

---

conf/graphTemplates.conf.example

Some new templates to offer single-hue lineColors.
ocean1
ocean2
forest1
forest2
sunset1
sunset2
moonlight1
moonlight2
lava1
lava2

New single-hue lineColors schemes

---

conf/graphTemplates.conf.example

Some new templates to offer single-hue lineColors. Ported from #1164.
ocean1
ocean2
forest1
forest2
sunset1
sunset2
moonlight1
moonlight2
lava1
lava2

New single-hue lineColors schemes (0.9.x)

---

webapp/graphite/render/functions.py

These seem to have been renamed some time ago.

Fix reference to renamed functions

---

check-dependencies.py
docs/config-local-settings.rst
examples/example-graphite-vhost.conf
requirements.txt
webapp/graphite/urls.py
webapp/graphite/wsgi.py
webapp/tests/test_util.py

This avoids the collectstatic step & apache configuration. It's probably slightly less optimal than serving files with apache/nginx but much easier to start with.
Whitenoise is compatible with Django 1.4 and above.

Serve staticfiles in the webapp if whitenoise is installed

---

webapp/graphite/render/functions.py

Checking `key` for membership in `metaSeries.keys()` is inefficient and
unnecessary since we can use the `setdefault` method to replace that
logic.
Additionally, the `keys` list appears to only be necessary for the
purposes of maintaining ordering; this can be managed instead by using
an OrderedDict instead of a dict and a list.

Use OrderedDict in groupByNode

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This seems to have been broken since the `system` argument to `legendValue()` was added in 1a826949732c394b03c7e2e94e65af82762b9103. `format_units()` already calls `abs()` as needed so we don't need to do so before passing the value into it.
/cc @jssjr

Preserve the sign of legendValue values when using a unit system

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py

Backporting PR #522 to the 0.9.x branch. This seems to have been in at one point; because the original patch for master (a different PR) was upported from 0.9.x. While testing 10.0-alpha with Grafana; the sortByName() Function did just that..function. When reverting back to the latest 0.9.x source; the function caused all of my grafana panels to go blank. Panel was calling for a function that's not in 0.9.x.
see (https://github.com/grafana/grafana/issues/690) for more details.

backport sortByName() to 0.9.X

---

docs/render_api.rst
webapp/graphite/render/evaluator.py
webapp/graphite/render/grammar.py
webapp/graphite/render/views.py
webapp/tests/test_render.py

Adds a `template()` function which acts kind of like a search/replace + eval. Any references to `$var` inside the template are replaced with a corresponding value.
The `template()` function takes both positional and kwargs. Positional args are numbered (i.e. `$1`, `$2`) and values can be passed in either as args or via the requests' query parameters. You can also provide both, to use the positional argument as a default but allow it to be overridden by the request:
```
/render?target=template(sumSeries(hosts.$1.cpu-*.idle.value),"fe1")
/render?target=template(sumSeries(hosts.$1.cpu-*.idle.value))&template[1]=fe1
/render?target=template(sumSeries(hosts.$1.cpu-*.idle.value),"fe1")&template[1]=fe*
```
Kwargs are named, and can also be passed in via the query parameters:
``` …
```

Add template() function to parameterize seriesList arguments

---

docs/tools.rst

Original link (http://code.google.com/p/jmxtrans) says nothing but:
"This project has moved to Github: https://github.com/lookfirst/jmxtrans"
Going to this link says:
"The repository has moved to our new organization at: https://github.com/jmxtrans/jmxtrans"
That is the actual repo. Updated the tools.rst with the proper current location of the repo.

Fixed jmxtrans URL

---

check-dependencies.py

Fixes #1081. Unnecessary since we [vendor pytz](https://github.com/graphite-project/graphite-web/tree/0.9.x/webapp/graphite/thirdparty) in 0.9.x.

Remove pytz dependency check (0.9.x)

---

webapp/graphite/render/functions.py

Renders a fallback metric when no series are provided. This is helpful for preventing "No Data" graphs.
For example, I am using `fallbackSeries(  maximumAbove(queue-*.jobs, 0),   queue-high.jobs  )` to show the job queues with the most jobs (hiding any with 0 jobs), or if all jobs are empty showing a 0 line for just the high queue.

Add fallbackSeries function

---

webapp/graphite/render/functions.py

timeShift was supposed to return a target name like:
timeShift(Sales.widgets.largeBlue,"-7d")
However, due to missing Quotation marks the actual result was:
timeShift(Sales.widgets.largeBlue,-7d)

Added missing Quotation marks for timeShift target name.

---

requirements.txt
tox.ini

Django 1.8 doesn't work with django-tagging < 0.3.5.
Fixes: #1249
Merging a totally unrelated PR "broke the build" and this fixes it.

Make 'pip install -r requirements.txt' work again

---

webapp/graphite/wsgi.py

and throwing errors when it's installed. Fixing issue https://github.com/graphite-project/graphite-web/issues/1252

Whitenoise is not working with python 2.6

---

webapp/graphite/util.py

This fixes #1142.
If we don't know our timezone, use TIME_ZONE from our local_settings.py configuration.

Supply a default timezone if none exists.

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Dispatch match results as individual series lists of length one to the arguments of the called reduction function.
This would resolve #1066 and is related to #1015.

Adapt reduceSeries to match the documentation

---

.travis.yml
tox.ini

This should speed up travis builds. An update of the `mock` library also broke all python2.6 builds.

Travis container infrastructure

---

tox.ini
webapp/tests/test_attime.py

As I was trying to figure out what was happening in the attime class, I ended up writing a test suite. Although it probably has holes, I believe it is already useful.
All tests are passing, except the one for parsing 'noon+yesterday' as per the Render API documentation, which is skipped.

Add unit tests for atttime class

---

webapp/content/js/dashboard.js

Allow the creation of a graph from a metric.  For example, you can paste in 'sumSeries(carbon.carbon-daemons.\*.cache[0-9]\*.metrics_received)' into the input box and a new graph with be created with that metric.

Add target to create a new graph from a metric.

---

webapp/tests/test_attime.py

Just like for #1276, as I was trying to understand what was going on with `summarize`, I ended up writing a test suite (cc @SEJeff).

Add unit tests for parseTimeOffset in atttime class

---

webapp/graphite/render/datalib.py

thread.is_alive() need to be called for timeout check, exception is not rising for that - https://docs.python.org/2/library/threading.html#threading.Thread.is_alive
With this fix you will get an error in log when thread starts time-outing.

Small bugfix for remote fetch threads.

---

webapp/graphite/render/views.py

Check data not empty before adding to cache. Fix for #1278?

Fix clustered webapp race condition writing to cache

---

.gitignore
requirements.txt
webapp/graphite/render/attime.py
webapp/tests/test_attime.py

Changing `attime.py`'s treatment of relative times with specified timezones to have consistent behaviour with absolute times/restore behaviour from 0.9.12, as discussed in #1151

Relative time timezone fix

---

check-dependencies.py
conf/graphite.wsgi.example
docs/config-local-settings.rst
examples/example-graphite-vhost.conf
requirements.txt

This avoids the collectstatic step & apache configuration. It's probably slightly less optimal than serving files with apache/nginx but much easier to start with.
Whitenoise is compatible with Django 1.4 and above, but before version 2.0.2 it was compatible only with python 2.7, so in this version safecheck is included.
Tested with synthesize and manual whitenoise installation, but please check more.
Rebase of https://github.com/graphite-project/graphite-web/pull/1209

Backport of #1188 "Serve staticfiles in the webapp if whitenoise is installed" to 0.9.x

---

webapp/graphite/wsgi.py

WhiteNoise version 2.0.1 onwards now supports Python 2.6

Ensure WhiteNoise < 2.0.1 not used with Python 2.6

---

webapp/graphite/render/evaluator.py
webapp/graphite/render/functions.py
webapp/graphite/render/functions_test.py

Make normalize() accept empty series.
Remove useless double call.

Backport PR #646 and #1169 to 0.9.x

---

docs/who-is-using.rst

At GapLabs, a division of Gap Inc. we use Graphite as our key APM stack, so I am proud to showcase that info in this page that GapLabs uses Graphite as their APM tool.

Updated about GapLabs using Graphite..

---

webapp/graphite/templates/browserHeader.html

The background effects weren't filling the header frame properly. Before and after screenshots:

Fix browserHeader background fill

---

webapp/graphite/remote_storage.py

Same as https://github.com/graphite-project/graphite-web/pull/1308 but with python 2.6 fallback

Enable buffering in HTTPResponse objects (with python 2.6 fallback)

---

webapp/graphite/render/hashing.py
webapp/graphite/render/views.py
webapp/graphite/storage.py
webapp/tests/test_render.py

This is a quick hack to enable shared memcache support in a carbon cluster using replication factor >= 2. Appending the local node information to the hash key stored in memcache will prevent false positives from occurring while rendering (and caching) pickles for the upstream graphite-web responsbile for rendering the user specified format.
I don't love the implementation, but it seems to be working well in my limited tests. (Currently on an :airplane:, and I don't have a proper local cluster setup to test with.)
/cc https://github.com/graphite-project/graphite-web/issues/1022
/cc https://github.com/graphite-project/graphite-web/issues/1102
/cc https://github.com/graphite-project/graphite-web/issues/1037

Namespace the request-cache with the local node address

---

webapp/graphite/render/attime.py

Change instantiation of tzinfo object to match that in views.py because get_current_timezone() returns the LocalTimezone implementation of tzinfo which does not support 'localize' and results in an AttributeError

Update attime.py to use pytz

---

webapp/graphite/render/attime.py

Per https://github.com/graphite-project/graphite-web/pull/1180#issuecomment-143607429 flake8 is claiming an F401 but this seems wrong. We're using `timezone` in two locations in the file.
```
/home/travis/build/graphite-project/graphite-web/webapp/graphite/render/attime.py:18:1: F401 'timezone' imported but unused
ERROR: InvocationError: '/home/travis/build/graphite-project/graphite-web/.tox/lint/bin/flake8 /home/travis/build/graphite-project/graphite-web/webapp/graphite'
```

Bypass incorrect flake8 F401 warning

---

docs/config-local-settings.rst
webapp/graphite/account/ldapBackend.py
webapp/graphite/local_settings.py.example

This allows graphite to authorize to LDAP with the user supplied in the login
window instead of static user, similar to how Django LDAP does it.

Add LDAP user template.

---

webapp/graphite/readers.py

Hi!
there is fix for a bug on carbon-link cache: its not downscale value for lower retention interval.
Example:
lowest precision in archive 10s, for 1d - 60s, agg method -- average. Value sent to graphite: 0.1 (10 req/s for example)
10s: 0, 0, 1, 0, 0, 1, 0.1
60s: 0.5, 0.1 // 0.1 * 60 is 60 req/s, instead of 10.
This fix disable carbonlink query for requests with step higher than lowers pointPerSecond in archive.

[critical] fix bug on carbonlink cache

---

webapp/graphite/render/datalib.py
webapp/graphite/storage.py

We shouldn't merge CarbonLink results with Whisper results if the latter is pulled from a rollup archive. Proposed fix was merged to master in #1002, this is an attempt to port the same logic to 0.9.x.
/cc @penpen @jssjr @deniszh

Never merge CarbonLink results with Whisper rollups

---

webapp/graphite/render/views.py

Check that we have an actual `target` string or skip it. The `master` branch already has this fix, brought in during the megacarbon-ceres merge. Fixes #427 (or the master commit already did).

Skip empty target params

---

check-dependencies.py
docs/install.rst

As mentioned by @brutasse in https://github.com/graphite-project/graphite-web/pull/1343#issuecomment-145383535.

Zope.interface is not needed by webapp

---

docs/releases/0_9_13.rst

Starting in 0.9.x, then I'll cherry-pick over to master. This bears the question, should these be added to `docs/releases/0_9_13.rst`, or should we move these to a fresh `docs/releases/0_9_14.rst`? If we're really going to release the next version as **0.9.14**, I'm inclined to pretend that 0.9.13 never happened and just `git mv docs/releases/0_9_13.rst docs/releases/0_9_14.rst`.
/cc @deniszh @brutasse @jssjr @SEJeff @mleinart

Update the 0.9.13 release notes (0.9.x)

---

requirements.txt

mock is a test dependency and as such should not live in the requirements.txt file.
Its usage is directly specified in tox.ini
This was introduced in 64cf924 (#1157)

Remove mock from requirements.txt

---

setup.py

This removes the permission error caused by RTD's build environment changes.

Remove install section on RTD

---

webapp/graphite/render/functions.py

This commit adds an optional third parameter, ~~keySeries~~ referenceSeries, to transformNull().
This argument, if specified, governs that transformation of nulls should not
happen unconditionally on every data interval, but rather, on the condition
that the same data interval in any series of keySeries is also non-null.
The motivation for this functionality stems from the need to differentiate
between nulls that represent "zero" and those that represent "no data".
The parameter keySeries is used to identify the data intervals to which
there are data, so that transformNulls() can transforms nulls in such
intervals as unequivocal zeros.

add optional parameter referenceSeries to transformNull

---

docs/requirements.txt

I don't know why, but the RTD build passed on 0.9.x with these changes.
http://graphite-web.readthedocs.org/en/latest/

Update to same requirements as master

---

setup.cfg
setup.py

Please see https://github.com/graphite-project/graphite-web/issues/677#issuecomment-150974416

Trying to fix RTD builds for 0.9.x

---

docs/config-database-setup.rst
docs/config-local-settings.rst
docs/config-webapp.rst
docs/install.rst

Replace the empty "configuring webapp" doc which is effectively already covered in the local_settings doc and repurpose it for some database setup instructions. /cc @gwaldo 
Also a bunch of little cleanups and fixes on the config-local-settings doc.

Database setup doc

---

webapp/graphite/logger.py

The function log function is getting called with or without the handler (which is setup based on the settings). The problem is that if LOGGING is set to false and the function is getting called, it will show an error about missing handler.
This was the simplest fix for that, it should apply to 0.9.14 (had issues committing it to the tags/0.9.14 so I'm committing to this branch instead (it should apply to the whole branch anyhow).

Removing unnecessary call to log function when no handler

---

webapp/graphite/render/functions.py

This fixes `removeAbovePercentile()` and `removeAbovePercentile()` when we encounter an IndexError (caused by a lack of data). As @toote mentions in #1394, the 95th percentile of nulls is still null.

Continue on IndexError for removeAbovePercentile and removeBelowPercentile

---

webapp/graphite/render/functions.py

Natural sorting allows names containing numbers to be sorted more naturally, e.g:
Normal sort: server1, server11, server12, server2
Natural sorting: server1, server2, server11, server12
To do so we left pad all number sequences within a name with a variable number of
zeros depending on the length of the sequence :
- server1  -> server0000000001
- server11 -> server0000000011
- server2  -> server0000000002
Signed-off-by: Sylvain Rabot <sylvain.rabot@f-secure.com>

Add Natural Sorting to sortByName function (untested)

---

webapp/graphite/render/datalib.py

The 'else' condition in this statement needed to be a `break` statement when `seriesList` was a list we were iterating, to break out of the `seriesList` iteration. However, in https://github.com/graphite-project/graphite-web/commit/3a7e1a88cae0a7af5e850bbf4153d237428cd8cb `seriesList` was changed to be a `dict`. Unfortunately, the `break` statement was not removed, so we'd give up pulling in the results of our fetches if our series were consistent.
I changed the break to a `continue` because I liked the comment in the `else` block describing what it "means" to be there. We could alternately just remove the entire conditional.
With a `break` and some debug logging:
```
Wed Nov 18 14:03:27 2015 :: [stats_counts.worker.worker*.sessions.processed_per_min, 10.144.251.222:8180] 
Results found: …
```

Datalib: continue instead of break when we already have best-series

---

docs/render_api.rst

The documentation uses 'yDivisor' where it should be using 'yDivisors'
This also confused me a little as to what it meant by 'pretty', so I added an explanation of what the codes trying to do in deciding the number of divisors, which I think is what its trying to do but not 100%!

- correct yDivisor -> yDivisors and add an explanation of 'pretty'

---

webapp/graphite/carbonlink.py

when configured with CARBONLINK_HOSTS = []
- select_host fails with webapp/graphite/render/hashing.py, line 88, in get_nodes ZeroDivisionError: integer division or modulo by zero
- trying to get_connection on empty host list is waste of time (and fails similarly as select_host)

Fix: Issue: CarbonLink ignore CARBONLINK_HOSTS = []

---

webapp/graphite/render/attime.py
webapp/tests/test_attime.py

**The problem**: `parseTimeReference` is not time-zone aware, preventing users from rendering graphs with their requested time zone on the x-axis properly. See #1407 for more.
**The yak**: `parseTimeReference` does some ... *timezone unfriendly* ... manipulations of a naive time object, preventing us from simply passing `tzinfo` into it in lots of edge cases.
**The solution**: make `parseTimeReference` internally work in UTC, and then have `parseATTime` localize the output into the requested (or default) timezone. (as recommended by http://pythonhosted.org/pytz/#problems-with-localtime)

Update attime to use timezones properly

---

.travis.yml

Twisted 15.5 officially breaks Python 2.6 support so let's stop testing it.
refs https://github.com/graphite-project/carbon/issues/482

Stop testing python 2.6 (0.9.x)

---

.travis.yml
check-dependencies.py
tox.ini

Twisted 15.5 officially breaks Python 2.6 support so let's stop testing it. Also updating `check-dependencies.py` to require 2.7.
refs https://github.com/graphite-project/carbon/issues/482

Deprecate python 2.6

---

requirements.txt
setup.cfg
tox.ini

refs https://github.com/graphite-project/graphite-web/issues/1425

Django 1.9 breaks our models, avoid for now

---

docs/conf.py
tox.ini

For a full project build with Django 1.9, we need to wait for a new version of django-tagging. Graphite-web needs to stay on Django<1.9 for now.

Fix docs build with Django 1.9

---

webapp/graphite/render/datalib.py

Noticed in #1399 et al that the root exception's traceback is swallowed when data fetch returns an exception after retries are maxed out.
Instead, log the full traceback and re-raise the exception (giving the benefit of full Django Exception rendering) to help debug situations like these.
Similarly, tweak another few exceptions in datalib to be a bit more helpful, logging tracebacks when it makes sense to

Improve exceptions raised when fetching data

---

docs/conf.py
docs/requirements.txt

Another attempt…
Django 1.9 doesn't work yet because it needs django-tagging.
Django 1.8 either because some incompatible django-tagging forms are being imported.
So, fallback to Django 1.7 and still call `django.setup()` to avoid the `AppRegistryNotReady` error when loading the functions page.
My build: http://graphite-web.readthedocs.org/en/latest/functions.html

Docs: functions page

---

docs/config-local-settings.rst

Found a spelling mistake - `specifed` > `specified`

Fix typo in docs/config-local-settings.rst

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Added ~~`leastSquaresForecast `~~ `linearRegression` function for graphs the liner regression by least squares method.

Linear regression by least squares method

---

.travis.yml
requirements.txt
setup.cfg
tox.ini
webapp/graphite/browser/views.py
webapp/graphite/events/views.py
webapp/graphite/metrics/views.py
webapp/graphite/render/views.py
webapp/graphite/urls.py

I made the required changes to have it work with Django 1.9. Travis builds OK with Django 1.9 and I have been using this updated version on my own deployment. Here is an overview of the changes:
1. Update Travis build files (`.travis.yml` and `tox.ini`) to build with Django 1.9. Update django-tagging version as well.
2. Fix moved or removed references in Django like `django.contrib.sites.requests.RequestSite` and `django.template.base.add_to_builtins`
3. Replace `request.REQUEST` with `request.GET` and `request.POST` on a case-by-case basis.
4. Update Django version in `requirements.txt` and `setup.cfg`
This solves #1467

Support for Django 1.9

---

.travis.yml
tox.ini

- Run tests through coverage
- Get Travis-CI to upload them to CodeCov
Coverage will be computed for all test targets thanks to tox.
[See results on CodeCov](https://codecov.io/github/JeanFred/graphite-web)
(I’m usually going for Coveralls but as I quite impressed by CodeCov I thought I would give it a try. I think it’s a good pick but happy to change either way).
Later on we can look at adding some more bells and whistles like badge in ReadMe, posting on Pull Requests and so on :)
See #863

Add test coverage support

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Add a new function, named `applyByNode`, which allows applying arbitrarily complicated expressions around prefixes (up to a given node). The example I made (reproduced from the docstring):
```
applyByNode(servers.*.disk.bytes_*, 1, "divideSeries(%.disk.bytes_used, sumSeries(%.disk.bytes_*))")
```
This would first evaluate all common prefixes up-to-and-including node 1 of the given seriesList (`servers.a`, `servers.b`, etc), and then substitute that into the template string (I used `%` as a template placeholder, but would be fine changing it) and evaluate the given result string.
Some of this is possible with `mapSeries` and `reduceSeries`, but, for example, this particular example is either impossible or super-complicated unless you go out of your way to store a separate `total_bytes` …

add new function named applyByNode

---

docs/tools.rst

The Carbonate project has transitioned to the graphite-project organization.

Update Carbonate URL in tools page

---

tox.ini
webapp/graphite/finders/standard.py
webapp/tests/test_finders.py

When the `target` includes many metric paths (ex. `avg(test.host0.loadavg5, test.host1.loadavg5, ..., test.host1000.loadavg5)`), render URI API calls `os.listdir` many times and its response is slower.
This PR reduces `os.listdir` calls if the metric paths contain no wildcards.

Improve render API performance when the `target` includes many metrics.

---

webapp/graphite/local_settings.py.example
webapp/graphite/remote_storage.py
webapp/graphite/render/views.py
webapp/graphite/settings.py

In cases where each cluster member is using https.  The HTTPS does not attempt to perform any kind of authentication, but simply enables the servers to use https.  This was once asked for in #856.

Enable CLUSTER_SERVER to talk to each other using HTTPS

---

CONTRIBUTING.md
CONTRIBUTING_FOR_COMMITTERS.md
docs/storage-backends.rst
docs/tools.rst

@graphite-project/committers 
* rewording in storage-backends.rst
* placing the `Bryan's Graphite Tools` in the Misc tool section of tools.rst
On a side note, does anyone care for the annotations-style links in the tools doc?  I think I prefer the inline style like what Bryan used.  Thoughts?

Docs tweaks

---

webapp/graphite/remote_storage.py

Was receiving MemcachedKeyLengthError: Key length is > 250 with the following stack trace:
File "/opt/graphite/webapp/graphite/render/datalib.py", line 138, in fetchData
seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
File "/opt/graphite/webapp/graphite/render/datalib.py", line 101, in _fetchData
fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
File "/opt/graphite/webapp/graphite/storage.py", line 41, in find
remote_requests = [ r.find(query) for r in self.remote_stores if r.available ]
File "/opt/graphite/webapp/graphite/remote_storage.py", line 24, in find
request.send()
File "/opt/graphite/webapp/graphite/remote_storage.py", line 57, in send
self.cachedResult = …

Fix Memcache key length error

---

webapp/graphite/remote_storage.py

Commit 3d378b2f528d0040256055b2af85839813006411 changed it to REMOTE_FIND_TIMEOUT which I believe to be an error.

Set timeout in RemoteReader.fetch to be REMOTE_FETCH_TIMEOUT instead of REMOTE_FIND_TIMEOUT

---

webapp/content/js/dashboard.js

North navbar non-collapsed by default.
Collapse the navbar when loading a dashboard from a hash change. Unify the hash change code so loading the dashboard happens and the navbar is collapsed.
Don't animate the collapse of the navbar as it makes the loading of the dashboard more fluid.

dynamically collapse navbar on dashboard load

---

webapp/graphite/render/glyph.py

I've noticed that the handling of the y axis range and the choice of tic marks are often a bit strange. For example:
* For linear axes the "pretty values" are often not all that pretty. I don't think a human would usually choose tic marks like [0, 12.5, 25, 37.5, ...]; one would use [0, 10, 20, 30, ...]. And surely nobody would choose [0, 22.5, 45, 67.5, 90, ...] when [0, 20, 40, 60, 80, ...] is so close by.
* The handling of `yMax="max"` is totally broken.
* There are several places where rounding errors could cause labels to be omitted.
* Logarithmic tic marks are totally broken, too.
So I've completely rewritten the axis-handling code while retaining backwards compatibility of the parameters. The new code restricts the mantissas of tic mark steps to be [..., 0.1, 0.2, 0.5, 1, 2, 5, 10, …

Improve axis range and ticmark handling

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py
webapp/graphite/util.py
webapp/tests/test_functions.py

This will do the same as integral() function, except resetting the total to 0 periodicaly.
For example:
target=integralByInterval(company.sales.perMinute,"1d")&from=midnight-10days
This would start at zero on the left side of the graph, adding the sales each minute, and show the evolution of sales per day during the last 10 days.

adding an integralByInterval() function

---

webapp/content/js/dashboard.js

Remove outer call would fail to work properly if curly braces were used in inner calls.

Include curly braces in removeOuterCall conditionals

---

docs/render_api.rst
webapp/graphite/render/glyph.py
webapp/graphite/render/views.py

This is a very simple commit to allow for rendering PDF files through the render API. The documentation has been updated to reflect it.
I do a little hacky conversion from pixels to points so that the API is always using pixels instead of points.
Let me know if I forgot anything.

Allow for rendering PDF files

---

webapp/tests/test_util.py

Not cleaning up some test files resulted in other newly created tests failing.

Clean up all test files created in tests/test_util.py

---

setup.py

Similar to https://github.com/graphite-project/carbon/pull/564, we shouldn't be stomping config values if they already exist at install time.

Don't stomp on configs

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This is essentially a more powerful version of `groupByNode()` that allows grouping by multiple nodes.
We are evaluating graphite (through grafana) by producing various graphs based on our metrics and there some cases where we need to group a series list by multiple nodes. The tests should be clear on when that might be useful.
What concerns me is that we introduce a new version of an already present function, I am not sure if we can extend the functionally of `groupByNode()` to support multiple nodes. That could get tricky because of the parameter order and that might be difficult to express to other libraries that try to autocomplete graphite functions (like grafana).
The first commit adds tests for `groupByNode()` and can be merged as-is to master if you find it ok, I can also create a …

Implement groupByNodes() function

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py
webapp/tests/test_render.py

When we wanted to draw a graph with just a constantLine,
it raised a ZeroDivisionError.
This patch corrects this error.

Enable usage of constantLine function without any other target in the graph

---

webapp/graphite/remote_storage.py

When finding remote metrics, a single unavailable backend causes the
entire tree to be unavailable for two consecutive requests, as
graphite/metrics/views.py's find_view() raises an AttributeError rather
than marking the backend as failed, and continuing with others.
This is ultimately because remote_storage.py's get_results() fails to
check for errors before trying to work with the response from httplib.
This patch enables all other backends' metrics to be shown immediately
after a backend fails.

Gracefully handle offline cluster backends

---

webapp/tests/test_attime.py

* Add test for parseATTime(YYMMDD)
* Add tests for coverage of bug 551771

Bring render/attime.py to 100% coverage

---

webapp/graphite/render/glyph.py
webapp/tests/test_render_glyph.py

Code Enhancements:
* Add some defensive input checks in find_x_times and format_units
* Explicitly define self.span and self.binary in class _LinearAxisTics. It was being defined in method calls.
* Add/Improve docstrings
* Adjust logic in applySettings to set axistLimit
* Move minValue<maxValue check to reconcileLimits() from applySettings()
Standalone functions:
* Tests for format_units()
* Tests for find_x_times()
* Tests for toSeconds()
* Tests for sort_stacked()
* Tests for safeArgs()
* Tests for safeMin()
* Tests for safeMax()
* Tests for safeSum()
* Tests for any()
Classes:
* Tests for the _LinearAxisTics Class
* Tests for the _LogAxisTics Class

Adding test coverage for render/glyph.py mark ii

---

requirements.txt

django 1.9 removes the "syncdb" option that graphite's db deploy requires. Django 1.9 also no longer works with django-tagging 0.3.6, which is also a pinned requirement.

Pin Django <1.9

---

webapp/graphite/util.py
webapp/graphite/whitelist/views.py
webapp/tests/test_whitelist.py

I had this mostly together, so in light of issue #1569 and pull request #1570, I submit this for test cases before the wording changes.
* Fix graphite.whitelist.load_whitelist()
* Add test cases for show, add and remove
Of note, the load_whitelist() function was not working before this change.  If the preferred method is to read the blob in and use unpickle.loads(), then that can be done.

Coverage for graphite.whitelist

---

docs/tools.rst

From their site: https://diamond.readthedocs.io/en/latest/#repos
Historically Diamond was a brightcove project and hosted at BrightcoveOS. However none of the active developers are brightcove employees and so the development has moved to python-diamond. We request that any new pull requests and issues be cut against python-diamond. We will keep BrightcoveOS updated and still honor issues/tickets cut on that repo.
Wasn't sure if the docs (exists in this PR) or their Github repo (https://github.com/python-diamond/diamond) was more appropriate. Happy to update the PR if you'd like it to point to the repo instead.

Offical project exists here. Brightcove is deprecated.

---

webapp/graphite/render/attime.py
webapp/tests/test_attime.py

This is cherry picked from the 0.9.x branch with changes made to the tests to accommodate the changes to graphite/render/attime.py

ATTime: Make TimeZone Aware

---

webapp/graphite/render/functions.py

The previous version recomputed the whole sum at each iterations.
When the moving average window is large (a few days), it makes computation too long.
This change make computation time linear instead.
Change-Id: I15196441aefb35a2748eb24fb432d965a79ce435

Linear complexity for movingAverage function

---

webapp/graphite/render/functions.py

Events times are returned from db in UTC timezone. Convert them in local time to be aligned with query times.

Convert event time to local tz in events function

---

webapp/graphite/render/datalib.py
webapp/tests/test_functions.py

Without this testing equality of two TimeSeries will compare the list contents but not the private variables
Potential fix for #1589.

Implement __eq__ for TimeSeries.

---

webapp/graphite/local_settings.py.example
webapp/graphite/settings.py

While testing #1588 I noticed that rendering took a "long" time when `CLUSTER_SERVERS` was broken, even though the metrics were local. Our default `REMOTE_FETCH_TIMEOUT` value was set to **6.0**, an excessively high setting for most environments. Lowering this to a more sane default value of **3.0**.
@bmhatfield @drawks You guys see any reason this shouldn't go in?

Lower the default REMOTE_FETCH_TIMEOUT

---

webapp/graphite/render/glyph.py

Here is a test showing that `%l` in `strftime` can fail silently:
```
Python 2.7.10 (default, Aug 13 2015, 12:27:27) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> datetime.now().strftime("%a %l%p")
''
>>> 
```
The existing test does not catch this case. This patch fixes that.

'%l' can fail silently, updated percent_l_supported test

---

webapp/graphite/render/glyph.py

This PR is based on #1053 with minor whitespace fixes by me. The gist is that it's possible for a user to manually pass an unquoted hex value (e.g. `808080`) which will be interpreted as an integer. Note that this only works for all-numeric values. Any unquoted alphanumeric values (e.g. `ff0000`) will still raise an exception.

Allow setColor to recognize unquoted integers as hex values (0.9.x)

---

webapp/graphite/render/glyph.py

This is a port of #1596 (based on #1053) to the master branch. Please see the aforementioned for a full explanation.
P.S. It was cute of me to think I was clever enough to write any tests for `setColor` in glyph.py. /cc @cbowman0 in case he's feeling up to the challenge.

Allow setColor to recognize unquoted integers as hex values (master)

---

webapp/graphite/render/glyph.py

`areaAlpha` sets alpha transparency, `valueLabelsColor` sets the colour of the pie labels.
I'll send a separate PR with doc updates, as not much of the pie stuff is documented so I'll go through all of it as one thing.

- add areaAlpha and valueLabelsColor pie options

---

webapp/graphite/browser/views.py

The model returns the graphs sorted with "order_by('name')". This change ensures branch nodes are give priority over leaf nodes. Python's stable sort preserves the ordering by graph name.

fix ordering of sorting on saved graphs

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Convert the following methods in graphite/render/functions.py to use safeMin or safeMax as reported in issue #1598 
* maximumAbove()
* minimumAbove()
* maximumBelow()
* minimumBelow()
* highestMax()
Add test coverage
* Add tests for maximumAbove()
* Add tests for minimumAbove()
* Add tests for maximumBelow()
* Add tests for minimumBelow()
* Add tests for highestCurrent()
* Add tests for highest_max()
* Add tests for lowestCurrent()
* Add tests for currentAbove()
* Add tests for currentBelow()
* Add tests for highestAverage()
* Add tests for lowestAverage()
* Add tests for averageAbove()
* Add tests for averageBelow()

Coverage render functions

---

webapp/graphite/render/datalib.py
webapp/tests/test_functions.py
webapp/tests/test_render_datalib.py
webapp/tests/test_render_glyph.py

Added test coverage for TimeSeries class and the nonempty() function in render/datalib.py
* Change Timeseries.__eq__ to return False if the comparing object is not a TimeSeries.
* Adjust test for nPercentile() that started failing because of the __eq__ change

Add coverage for TimeSeries class

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

#1568 caused a regression
```
window_sum += last
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```
Where for a given window + preview was half None, half values.

Fix regression in movingAverage

---

webapp/graphite/render/glyph.py
webapp/tests/test_render_glyph.py

FYI @cbowman0 - I noticed this regression when I triggered a render that chose the following xAxisConfig:
```
dict(seconds=8000,        
minorGridUnit=DAY,   
minorGridStep=3.5,   # <--- float here
majorGridUnit=DAY,   
majorGridStep=7,     
labelUnit=DAY,       
labelStep=7,         
format="%m/%d",      
maxInterval=365*DAY),
```

Floating point values are valid when unit=DAY

---

webapp/graphite/readers.py

If one metrics stays in carbon-cache for too long(like over 1h
not committing to disk) and when we are querying one metrics within
that time, it's possible `i = int(interval - start) / step` is negative,
hence overwriting the correct value.

Fix: wrong metrics data when it takes a lot of time writing to db.

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

The ``aggregateLine`` function should be able to handle multiple series lists being passed to it.
Also adjusts the result name so that when calling with ``aggregateLine(foo-*.bar)`` it will return each match, instead of ``aggregateLine(foo-*.bar, 42), aggregateLine(foo-*.bar, 45), ...``

Handle multiple series in aggregateLine

---

docs/dashboard.rst
docs/render_api.rst
webapp/graphite/render/views.py

This supersedes #1172, introducing the `noNullPoints` param for removing null results in `format=json` output. The original work was submitted by @kokje. I've made a small change to the parameter name and documented the feature.

Option to filter null datapoints from json results

---

docs/config-local-settings.rst

@mauron85 pointed out in #890 that we need to specify the `PYTHONPATH` when running `django-admin.py`. His PR had some issues that have not been addressed so I'm fixing it here.

Missing PYTHONPATH in docs example

---

webapp/graphite/render/functions.py

While `sumSeriesWithWildcards` and `averageSeriesWithWildcards` both have correct documentation, `multiplySeriesWithWildcards` has incorrect and misleading one.

fix multiplySeriesWithWildcards docstring

---

check-dependencies.py
webapp/graphite/render/glyph.py

Earlier commits led us to prefer installing cairocffi over pycairo, but `glyph.py` would still use pycairo first if it was available. Let's fix this oversight.
/cc @SEJeff @anotherthomas (via #341) and @brutasse who were involved in the earlier Cairo discussions.

Prefer cairocffi, fall back to pycairo

---

webapp/graphite/render/glyph.py

Since version 1.1.6 pycairo text_path() has support of  text in unicode.

unicode support in drawing text

---

webapp/graphite/readers.py

The native Python wrappers for RRDTool reject Unicode filesystem paths.
Ensure paths passed to RRDTool are converted to use the file system
encoding.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>

fix #552: using rrdtool causes TypeError

---

webapp/content/js/dashboard.js
webapp/graphite/dashboard/views.py

Adapt the proposed fix by @kaarelk in #434, adding another fix to the UI sorting.

Sort dashboards by name in Finder

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Expanding upon pull request #717 from @bruce-lyft 
* Add tracking of the step to reflect when we're skipping over a None value.
* Add test case.

Interpolate across Nones in perSecond()

---

webapp/graphite/render/functions.py
webapp/graphite/render/glyph.py
webapp/tests/test_functions.py
webapp/tests/test_render_glyph.py

This PR supersedes #682, resolving a merge conflict and fixing the original change to pass tests. Fixes #671.
@toni-moreno I believe this accomplishes the same goal with less code. Please review and let me know if I left anything out.
Example:
```
target=cactiStyle(scale(collectd.graphite.filecount-whisper.files,20),"binary","b")
```

Support for cactiStyle unit suffix

---

webapp/graphite/metrics/views.py
webapp/tests/test_metrics.py

This is a new implementation of @toni-moreno's proposed change in https://github.com/graphite-project/graphite-web/pull/718. I believe this is a cleaner approach, extending `/metrics/find/` with a new `format=nodelist` parameter. The optional `position` parameter allows the user to override the default (`-1`) node index.
/cc @brutasse @cbowman0 
```
$ curl -k "https://127.0.0.1:443/metrics/find/?query=carbon.*.*.*&format=nodelist&position=2"
"{'nodes': ['vagrant-1']}"
$ curl -k "https://127.0.0.1:443/metrics/find/?query=carbon.*.*.*&format=nodelist"
"{'nodes': ['activeConnections', 'avgUpdateTime', 'blacklistMatches', 'cache', 'committedPoints', 'cpuUsage', 'creates', 'droppedCreates', 'errors', 'memUsage', 'metricsReceived', 'pointsPerUpdate', 'updateOperations', 'whitelistRejects']}" …
```

Add nodelist format to metrics find view

---

webapp/graphite/render/functions.py
webapp/graphite/render/views.py
webapp/tests/test_functions.py

This PR supersedes #493, introducing the `verticalLine` function by @nharkins. I've resolved merge conflicts and enhanced the function documentation a bit. Took a stab at a unit test but I'm hitting problems with the attime stuff.
/cc @cbowman0 for his usual testing brilliance

Add verticalLine function

---

webapp/graphite/render/datalib.py
webapp/tests/test_functions.py
webapp/tests/test_render_datalib.py

The color attribute is not expected to always be there.  If it does exist, then check for equality.
I'm not 100% satisfied on the pythonic way of doing this sort of logic, so code cleanup suggestions is welcome.

Make Timeseries equality test check for color

---

webapp/graphite/compat.py
webapp/graphite/events/views.py
webapp/tests/test_events.py

First small step towards REST-ifying our Events support. There are no native consumers for this but it drives me nuts that you'd have to dump all events (`/events/get_data`) to inspect a single event from the command-line.
```
$ curl -s -k -H "Accept: application/json" "https://127.0.0.1/events/4/" | json_pp
{
"id" : 4,
"tags" : [
"deploy",
"stupid"
],
"what" : "Event - deploy",
"data" : "",
"when" : 1469714975
}
```
Need to add a test for this before we merge. Will try to get this done soonish unless @cbowman0 beats me to it.

Ability to GET single event in json

---

webapp/graphite/local_settings.py.example
webapp/graphite/settings.py

Expose django-tagging MAX_TAG_LENGTH setting

---

docs/events.rst
webapp/graphite/events/compat.py
webapp/graphite/events/models.py
webapp/graphite/events/views.py
webapp/tests/test_events.py

This introduces two new filtering options for searching events+tags. Turns out that graphite-web has used django-tagging's `with_all()`, returning a "lazy union" that is surprisingly unintuitive (see #1210).
With this change we're adding a mixin to expose django-tagging's `get_intersection_by_model`, and extending our Events model to accept a `set` param that lets the user select among the different set types:
* union
* intersection
* "lazy union" (legacy, default)
Fixes #1210.

Tagging mixin to support set return types

---

docs/render_api.rst
webapp/content/js/composer_widgets.js
webapp/graphite/render/glyph.py

This introduces a new param `hideNullFromLegend`. When enabled, any series with all null values will be hidden from the legend. Originally conceived in #150, alternative solution proposed in #1618.
/cc @bryantsai
P.S. Apologies for the comment-fix noise, they were driving me nuts.

New hideNullFromLegend feature

---

bin/build-index
bin/build-index.sh

The "build-index" scripts have been broken in master for a while. This includes a fix for modern Django as well as a path fix for the wrapper script.

Fix metric index build scripts

---

webapp/graphite/finders/__init__.py
webapp/graphite/finders/ceres.py
webapp/tests/test_finders.py

Using curly braces resulted in failed lookups with the Ceres finder because the python glob function doesn't handle them.
Mentioned in #1218 and #256

Fix Ceres Finder to allow curly braces in metrics find requests

---

webapp/content/js/browser.js

This builds on the work recently merged in #1652. Rather than attempting to refresh at the specific node level, refresh the entire branch. This has the added benefit of allowing us to refresh `MyGraphs` and `User Graphs` at the same time. It also addresses the problem I noticed where it wouldn't notice new root nodes.
I've also update the tree name from `Graphite` to `Metrics` to match the change in #560 against the 0.9.x branch.

Improved Metrics tree refresh

---

webapp/graphite/metrics/views.py
webapp/tests/test_metrics.py

This PR supersedes #733. Aside from rebasing, I've also added a handful more jsonp responses, fixed a potential minor bug with not allowing a single `CLUSTER_SERVERS`, and a test for cluster failures.
@cbowman0 Any ideas on how we could add a positive cluster query in our tests?

Fixed jsonp support for metrics view

---

webapp/graphite/render/functions.py

This PR supersedes #982, resolving conflicts. Thanks to @andrewbaxter for this change to pad the `dividendSeriesList` with nulls when a series goes out of scope.

Handle missing divisor series in divideSeries gracefully

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This PR supersedes #984, adding a `delay()` function by @andrewbaxter. From his original description:
"This delays a series by a number of time steps. The delay method is the same as in derivative (Nones appended to the beginning).
Our immediate use case is computing a derivative using divideSeries, to find the percent difference from the previous data point."
The original feature branch has been deleted, making `git am` a painful affair. I've had to re-commit his original work with a couple fixes along the way.

Delay function (rebased)

---

webapp/tests/test_metrics.py

A local running Graphite listening on 0.0.0.0 will cause this test to fail. Disable for now or until we have a better story around testing clusters.

Disable cluster failure test for now

---

webapp/graphite/metrics/views.py
webapp/graphite/render/glyph.py

This PR supersedes #120 and fixes #242, merging conflicts and making a couple minor changes.
In some cases, users may wish to encode special characters into their metric names. With this change, graph legends and the metrics tree will show the unencoded version of the metric name (although the actual graph link remains encoded).
Tested an encoded metric name:
```
$ echo "foo.xxx.%28bar%29test%7E 1 `date +%s`" | nc localhost 2003
```
Visibly unquoted metric name in the metrics tree and graph legend, but still encoded in the actual query:

Unquote metric/target names

---

webapp/graphite/local_settings.py.example

A "missing" instance of `DEFAULT_CACHE_DURATION` was added to `local_settings.py.example` in  037f05d even though it was in fact already added back in f18bb3c. Let's remove the latter since the former is grouped with similar settings.

Duplicate instance of DEFAULT_CACHE_DURATION setting

---

webapp/graphite/render/functions.py

This is to fix `aliasByNode()` throwing an exception when the optional `referenceSeries` parameter is specified to `transformNull()`.

Fix regression to aliasByNode caused by transformNull

---

.gitignore
webapp/graphite/render/datalib.py
webapp/tests/test_datalib.py

This PR resolves issue #1671 
The problem was that if it takes a long time writing data to disk, the carbon-cache will hold the results in memory. When graphite-web asks carbon for its data, it gives him the entire cache, which may hold older data than the query's time frame. The ``mergeResults`` function doesn't handle this scenario properly, and will mistakenly return the cache data, even though it is irrelevant.
Note that this issue exists in [master](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers.py#L144) as well, however, only in the ``CeresReader``.
Should i create a PR against master as well?

Fix datalib mergeResults function to properly handle time frames that are in the future compared to the cached results

---

.gitignore
webapp/graphite/readers.py
webapp/tests/test_readers.py

This PR resolves issue #1671 for the master branch.

Fix CeresReader fetch function to properly handle time frames that are in the future compared to the cached results

---

docs/install-pip.rst
docs/install.rst

As reported in #1509 the docs didn't really work for pip installations. Some of this is due to the mismatch between PyPi packages and our "latest" docs, while other stuff includes outdated dependencies. There is still more work to be done but this is a start.

Fix install docs for pip

---

setup.py

When installing via pip we should handle these dependencies automatically, like Carbon does with Twisted.

Add install_requires for pip

---

docs/install-pip.rst

Need to mention the development headers for Cairo and libffi.

Mention cairo and libffi development headers for pip install

---

webapp/content/js/dashboard.js

Issue #475 - absolute time-range for a dashboard can be passed using "from" and "until" GET-parameters in the URL (http://graphite/?from=2013-10-27T22:00:00&until=2013-10-27T23:00:00#cpu - to open the CPU dashboard in the given time range). Format of the time range boundaries is "YYYY-MM-DDThh:mm:ss"

Issue #475 - absolute time-range for a dashboard from the URL

---

docs/config-database-setup.rst

Starting a required directive for creating the default django db with "remember," is not clear. I reworded and made it not a note, as it's a requirement to make this functional.

Changed wording for clarity.

---

requirements.txt

Use the most up to date security / bugfix minor version of Django available instead of only 1.9.0.
Not using `Django>=1.9,<1.10` syntax due to https://groups.google.com/forum/#!msg/python-virtualenv/DvG1InRGdR0/14b9CISO2AcJ

Use latest minor Django version

---

webapp/graphite/finders/__init__.py

According to @iain-buclaw-sociomantic comments in https://github.com/graphite-project/graphite-web/pull/1713/files `expand_braces()` is not really optimized.
I tested that using `timeit` - https://gist.github.com/deniszh/1e7eb64cb372d83d9ecd46d11c813193
According to tests, optimized version is 20% faster, so, it's worth trying.
Also change indentation back to 2 spaces.

Optimizing brace expansion

---

webapp/graphite/finders/__init__.py

The conditional in get_real_path only worked when the file was a symlink.
This changes it so that if any part of the path is a symlink, then obtain the real metrics path, so that carbonlink lookups work.

Enhance get_real_path to handle symlinks in any part of the path

---

webapp/graphite/finders/__init__.py
webapp/tests/test_finders.py

Proposed fixes for #1740.
Adjust EXPAND_BRACES_RE to match {} without anything inside of it.
Change expand_braces to expand `{foo}` to `foo`.
Add a handful of unit tests for different brace usages.

Fixes for issue #1740

---

webapp/graphite/readers.py
webapp/tests/test_finders.py

Fix the GzippedWhisperReader get_interval method to work
Add a little bit of coverate for finder of gzipped whisper files.

Add more test coverage for standard finder

---

webapp/graphite/render/functions.py
webapp/tests/test_events.py

For example combining timeShift or movingAverage with events throws the following exception.
Example query
`http://host/graphite/render?target=timeShift(transformNull(events("tag")), "1d")&from=-7d`
```
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
response = callback(request, *callback_args, **callback_kwargs)
File "/opt/graphite/webapp/graphite/render/views.py", line 125, in renderView
seriesList = evaluateTarget(requestContext, target)
File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
result = evaluateTokens(requestContext, tokens)
File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
return evaluateTokens(requestContext, …
```

Failing functions when combining with events

---

requirements.txt
setup.py
tox.ini

This reverts commit be7fca6e436a42b0bc4ee0f5c005395c6deb901c.
The `~=` requirement syntax isn't supported by older pip releases including but not limited to 1.5.4, see #1753 for further discussion.

Revert "update django version specifier syntax"

---

webapp/graphite/render/hashing.py

Proper hex conversion for fnv1a_ch in 0.9.x

---

CONTRIBUTING.md
requirements.txt
webapp/graphite/render/float_encoder.py
webapp/graphite/render/views.py
webapp/tests/test_render.py

- The 'json' and 'jsonp' formats output float('inf') as 1e9999, float
('-inf') as -1e9999, and float('nan') as null
- The 'dygraph' format (a JSON-based format) outputs the same as
Infinity, -Infinity, and null (see http://dygraphs.com/tests/gviz-infinity.html)
- Minor updates to documents to make sure commands can be run without errors or problems

Render infinite values to valid JSON values. Fixes #813

---

webapp/graphite/render/glyph.py

Don't add padding (5px) for each line of legend; only add it
once to separate the graph area from the legend.
Before and after fix graphs:
1 line: http://tinypic.com/r/muabys/9
5 lines: http://tinypic.com/r/2wmniiv/9
6 lines: http://tinypic.com/r/23h7lgw/9
5 lines, with the fix: http://tinypic.com/r/2db2i6f/9
6 lines, with the fix: http://tinypic.com/r/2s8pvzn/9

webapp/glyph.py: fix blank space below the legend

---

webapp/graphite/node.py
webapp/graphite/readers.py
webapp/graphite/remote_storage.py
webapp/graphite/storage.py
webapp/tests/test_finders.py

- readers: be more resilient to the loss of a single backend
- storage: try to shuffle nodes
- finder: avoid calling get_intervals() when listing metrics

Improved stability/performance for storage

---

webapp/graphite/readers.py

This method gets called with the rollup aggregation method specified in the whisper file; Whisper supports the "last" aggregation method (as per <http://graphite.readthedocs.io/en/latest/whisper.html#rollup-aggregation>). This patch fixes reading whisper files with their aggregationMethod set to "last".

support whisper aggregation method "last" in readers.py

---

webapp/graphite/account/views.py
webapp/graphite/browser/views.py
webapp/graphite/composer/views.py
webapp/graphite/metrics/views.py
webapp/graphite/render/views.py
webapp/graphite/user_util.py
webapp/graphite/util.py
webapp/tests/test_user_util.py
webapp/tests/test_util.py

In recent versions of Django you can't import models until
late in the process, which is an issue because util.py does that
and is imported all over the place, including by readers.py.
Since readers.py is a kind of external API (mainly for FetchInProgress
we need to make sure it is easilly importable).

Make readers.py more easilly importable by moving away models

---

webapp/graphite/render/datalib.py

This patch simply moves the definition of `_fetchData` out of `fetchData` and makes it a separate top-level function.
The advantage of this change is that it makes it easier for a user to understand the logic flow in `fetchData` as it's no longer interrupted midway by the definition of `_fetchData`.

move _fetchData out of fetchData

---

webapp/graphite/node.py
webapp/graphite/readers.py
webapp/graphite/remote_storage.py
webapp/graphite/render/attime.py
webapp/graphite/render/datalib.py
webapp/graphite/render/views.py
webapp/graphite/util.py

This patch sends a 'now' query parameter in requests to backend hosts in the same way as the 0.9.x branch.
It also passes `requestContext` through to `RemoteReader`, where it isn't used yet but will be by #1736 and #1818

pass consistent 'now' value to backend nodes

---

webapp/graphite/intervals.py
webapp/graphite/metrics/views.py
webapp/tests/test_metrics.py

This patch adds a lightweight json output format option for find requests.  It was initially implemented as part of the work on clustering.  The json format is pretty simple, supporting leaf and branch nodes and looks like this:
```
[
{
"is_leaf": true,
"path": "carbon.agents.dev-a.cpuUsage",
"intervals": [
{"start": 1478989692.654787, "end": 1486765671.553646}
...
]
},
{
"is_leaf": false,
"path": "carbon.agents.dev-a"
}
...
]
```
It also supports the jsonp parameter with the same semantics as the existing `completer` format and is roughly 20% more compact than the existing `pickle` encoding.

add json format option for find api

---

webapp/graphite/local_settings.py.example
webapp/graphite/remote_storage.py
webapp/graphite/render/datalib.py
webapp/graphite/render/views.py
webapp/graphite/storage.py
webapp/tests/test_render_datalib.py

This patch implements support for the REMOTE_STORE_FORWARD_HEADERS config option, and adds some supporting changes for #1818.  The general approach is the same as #1736 and if desired we could apply that separately which (after some cleanup & conflict resolution) would reduce this patch to an update to  pass an explicit "now" value to backends, make the requestContext available in more places, and some other supporting refactor work to reduce the size of the #1818 patch.

supporting refactors for #1818

---

setup.py
webapp/graphite/render/grammar.py

By using a Regex parser instead of building the rule we are able to get rid of the concurrency issue while loading multiple graphs.
From Paul McGuire, Pyparsing author :
> That KeyError is being raised inside the collections.OrderedDict code, and the key is extracted just a couple of lines prior to the place where the exception is raised, so we know it is a valid key. But there is a (small) window of time in which the same key could be popped by two different threads, and so the second thread will fail as the key will no longer be there.
> I've found in other parsers that building up numeric values with Combine, Word, etc. is a real slowdown compared to using a Regex, and there is not that much loss in readability or maintainability. These re's aren't that long or complicated.

Remove pyparsing pinning requirement

---

webapp/content/js/dashboard.js

This stops the Dashboard screen from flashing blank images and being distracting to look at.

Pre-load each graph image before updating the dashboard UI

---

docs/install-pip.rst

debian 8 needs build-essential or at least some of it's components to compile twisted

debian 8 at least needs build-essential

---

webapp/graphite/render/glyph.py

When passing an URI-encoded string (e.g. '&title=Hello%20World%21'), display 'Hello World!' instead in graph title.
Graph before the fix:
Fixed version:

webapp/glyph.py: fix incorrect display of 'title' URI parameter

---

setup.py

using:
pip install https://github.com/graphite-project/graphite-web/tarball/master
Is currently broken as worker_pool is not included in the list of things to install. I've added that and installed successfully via my own fork.

Update setup to include worker_pool to fix install

---

webapp/graphite/carbonlink.py

Sympton:
```
2017-04-05,17:45:51.784 :: Failed CarbonLink query 'carbon.agents.casar1_fyre_ibm_com-c.cache.queries'
File "/opt/graphite/webapp/graphite/readers.py", line 211, in fetch
cached_datapoints = CarbonLink().query(self.real_metric_path)
AttributeError: 'NoneType' object has no attribute 'query'
```
GlobalCarbonLinkPool.instance() is called to return global singleton, but the return function is missing. This causes carbon queries to fail with above message.

CarbonLink() must return singleton to be accesible

---

webapp/graphite/metrics/views.py
webapp/tests/test_metrics.py

This should avoid calling the database for every /metrics/find
request in clustered environments.

Only fetch user profile when it's needed

---

webapp/graphite/render/datalib.py

This patch fixes an issue when using multiple targets in a single query with remote prefetch enabled.
Without this patch, a query with 2 targets will return the results twice, a query with 3 targets will return them 3 times, etc.
To test, try a query like `ttp://localhost:8000/render?format=json&target=collectd.*.cpu-0.cpu-idle&target=collectd.*.cpu-1.cpu-idle&from=-1min`

Duplicated results when using remote prefetch with multiple targets

---

webapp/graphite/remote_storage.py

This patch alters the prefetch code to use a single backend request to each cluster host rather than a separate request for every target.
This is possible now because of the alterations to the way prefetch works implemented in #1818

use a single prefetch request for each cluster host

---

webapp/graphite/remote_storage.py

This prevent stuff like:
```
GET /metrics/find/?local=1&format=pickle&query=%2A HTTP/1.1
Accept-Encoding: identity
Client-IP: None
HTTP_REFERER: None
```

remote: do not forward non-present headers

---

docs/config-local-settings.rst

Looks like the docu is still showing the old config (pre 1.0) arguments for the cluster settings which is a little bit misleading. I have modified and added the arguments based on local_settings.conf.example from 1.0.1.

Update local_settings cluster config documentation

---

webapp/graphite/remote_storage.py

if `REMOTE_PREFETCH_DATA` is on and no targets are passed then there's an exception in the worker pool which gets swallowed. This happens due to the `RemoteReader`'s `self.bulk_query` being set to `[None]`.:
```
2017-05-19,17:21:02.768 :: thread Thread-5 at 1495214462.768827s ReadResult:: Error requesting http://mt-read-12574-small-ops:6060/render/?format=pickle&local=1&noCache=1&from=1495214162&until=1495214462&target=None&now=1495214462: 'NoneType' does not have the buffer interface
File "/opt/graphite/webapp/graphite/remote_storage.py", line 303, in _fetch
timeout=settings.REMOTE_FETCH_TIMEOUT,
File "/opt/graphite/local/lib/python2.7/site-packages/urllib3/request.py", line 70, in request
**urlopen_kw)
File …
```

prevent exception on no targets

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This expands on #1936 to allow more control over how the resulting aliases are formatted.

use sprintf-style format strings in aliasQuery

---

docs/carbon-daemons.rst
webapp/graphite/local_settings.py.example
webapp/graphite/logger.py
webapp/graphite/settings.py
webapp/graphite/storage.py

This is kind of a "slow query" log. This allow the administrator to abort huge requests before they impact everybody.
A finder/reader could use these settings to abort early instead of doing it a the end, but this isn't implemented yet.
cc: @Thib17

Add settings to limit metrics fetched by queries

---

webapp/graphite/settings.py

LDAP_BASE_USER/LDAP_BASE_PASS setting has been broken since
the LDAP_USER_DN_TEMPLATE setting was introduced in commit
871a6cb427cbb1d8a1c33905d6f25e4b39d8a5b7.
By not giving LDAP_USER_DN_TEMPLATE a default value in
settings.py, the expected attribute could not be fetched in
ldapBackend.py and logins fails with:
AttributeError: 'Settings' object has no attribute
'LDAP_USER_DN_TEMPLATE'

LDAP broken since Graphite 1.0

---

webapp/graphite/finders/remote.py
webapp/graphite/readers/remote.py
webapp/graphite/render/datalib.py
webapp/graphite/render/evaluator.py
webapp/graphite/render/utils.py
webapp/graphite/render/views.py
webapp/graphite/storage.py
webapp/tests/test_render.py

This set fixes two bugs I discovered with the latest changes:
* When *not* using REMOTE_PREFTECH_DATA the code checking in flight requests suffered from a performance regression (re-fetching urls each time)
* When using REMOTE_PREFTECH_DATA and `timeShift()` the wrong data was behind used since we didn't check the start and end time of the query.

Remote storage fixes

---

webapp/graphite/render/functions.py

Default is '7d' - one week, as before. Format - same as for all others time intevals in Graphite.
Fixing #1957

Introducing bootstrapInterval for HoltWinters functions

---

webapp/graphite/render/functions.py

Backport of  PR #1965 to 1.0.x
Default bootstrapInterval is '7d' - one week, as before. Format - same as for all others time intervals in Graphite.
Fixing #1957

Introducing bootstrapInterval for HoltWinters functions 

---

webapp/graphite/util.py
webapp/tests/test_util.py

This patch makes a couple of changes to the way that `is_local_interface` works, which allow it to work consistently across hosts with and without IPv6 interfaces.
- detect IPv6 based on the number of colons, an IPv4 address will always have 0 or 1
- test the given hostname for local-ness by attempting to bind to it as a source address rather than connecting to it and seeing whether the local (source) ip matched
- change behavior for `::1:8080` which is treated as a valid IP on hosts with IPv6 connectivity
- add tests for checking local-ness of dns names as well as ip addresses

is_local_interface and IPv6

---

webapp/graphite/render/attime.py
webapp/graphite/render/views.py
webapp/tests/test_attime.py

Currently time specifications like `midnight` are always treated as being relative to UTC, this patch changes them to be treated as relative to the specified timezone, either from the `tz` parameter in the request or the `TIME_ZONE` setting.  This changes the counter-intuitive behavior reported by @Dieterbe in #639 
This does represent a fairly significant departure from the current behavior, albeit one that I think makes things much more sensible from a user perspective.

make attime specifications honor the requested timezone

---

webapp/graphite/dashboard/views.py

This improves speed of loading the dashboard finder window because it does not query and sort the state column where it doesn't need it.

Change dashboard find to only query for the name

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Backport of "divideSeriesLists function #1928" to 1.0.x

Backport of "divideSeriesLists function #1928"

---

webapp/graphite/app_settings.py
webapp/graphite/settings.py

Backport of "settings: make sure one can override CACHES in local_settings.py #1959" to 1.0.x

settings: make sure one can override CACHES in local_settings.py

---

webapp/graphite/metrics/views.py
webapp/tests/test_metrics.py

This patch updates metrics/find to use the same parsing library for from/until dates as render does, to keep things consistent across the endpoints.

update metrics/find to support the same from/until specifications as render

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

When processing data, various normalization and scaling techniques are utilized, and a very popular technique is Min-Max normalization. I have noticed that many people use this technique, especially when working with various machine learning algorithms, to process raw data, which is why I thought this function should be added as a graphite function. The formula is very simple, for each point do the following: (point - min) / (max - min). You can read more about it here: http://sebastianraschka.com/Articles/2014_about_feature_scaling.html#about-min-max-scaling
I have tested this new function on my own simple graphite server. If you want to see how it normalizes raw data live then look at: http://34.207.148.148/render/?target=minMax(collectd.ip-172-31-22-200_ec2_internal.entropy.entropy) …

Min-Max Normalization Function

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

As reported in #2028 there is an issue with how null values are handled in `perSecond`, it doubles the step value for every null encountered instead of incrementing it by the series step.  This has been corrected and the test suite has been updated to test the scenario where multiple null values are encountered.
While debugging this issue I saw that there are many places in `functions.py` including in `perSecond` where the code is reliant on the non-intuitive Python 2.3-2.7 behavior where the division operator `/` performs integer/floor division if both arguments are integers and regular division if one or more are floats.
See https://www.python.org/dev/peps/pep-0238/ for a discussion of division in Python and the changes introduced in 2.3 and in 3.0.
To both make it clearer in the code …

fix perSecond null handling, use explicit integer division

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This PR centralizes processing for the `movingAverage`, `movingMedian`, `movingMin`, `movingMax` & `movingSum` functions into a new `movingWindow` function which they all now use internally, removing a lot of duplicated code.  It also adds a new `xFilesFactor` parameter to all those functions which allows the user to specify a value between 0 and 1 to indicate what fraction of the points within the window must be non-null for the output to be considered valid.
It also updates `exponentialMovingAverage` to match the implementation of `movingWindow` as much as possible, and fixes an issue when using it on fractional series where the first result datapoint is not rounded but the subsequent points are all rounded to 3 decimal places.  It now consistently rounds to 6 decimal places, which …

implement movingWindow & round functions, tidy up other "moving" functions

---

webapp/graphite/tags/localdatabase.py
webapp/graphite/tags/redis.py
webapp/graphite/tags/urls.py
webapp/graphite/tags/utils.py
webapp/graphite/tags/views.py
webapp/graphite/urls.py
webapp/tests/test_tags.py

This PR adds support for a `/tags/findSeries` endpoint that can be used to look up series via the same logic as `seriesByTag`, and adds support for passing a `filter` parameter to `/tags` and `/tags/<tag>` to filter the returned tags & tag values respectively.  It also adds support for a `pretty` parameter to return formatted json from those endpoints.

add /tags/findSeries, add filter and pretty parameters to tag list/details endpoints

---

docs/render_api.rst
docs/tags.rst
webapp/graphite/render/evaluator.py
webapp/graphite/render/functions.py
webapp/graphite/render/grammar.py
webapp/tests/test_functions.py

This PR adds support for chaining functions together by "piping" the output of each function into the next (as the first parameter), much like the way they're presented in the Grafana UI.
When dealing with deeply-nested queries this keeps the arguments for each function together, and can help increase readability vs the current "nested" syntax.
With this update the following query:
```
aliasByNode(movingAverage(sortByName(test.*),"5min"),1)
```
can be written as:
```
test.*|sortByName()|movingAverage("5min")|aliasByNode(1)
```
or:
```
sortByName(test.*)|movingAverage("5min")|aliasByNode(1)
```
Piping is supported within function arguments, so the same expression could also be written as
```
movingAverage(test.*|sortByName(),"5min")|aliasByNode(1)
```
A more useful example would be …

support "pipe" function chaining syntax

---

webapp/graphite/render/functions.py

In much the same way that `movingWindow` provides a centralized implementation for the various `moving*` functions and added support for additional aggregation methods, this PR defines a new `aggregateWithWildcards` function that provides a single implementation for all `*SeriesWithWildcards` functions and adds support for using all defined series aggregator function with wildcards (full list is in the docs).
It also includes a minor refactor for `movingWindow` to take the block that defines the aggregation func outside the loop.

add aggregateWithWildcards function, minor refactor for movingWindow

---

webapp/graphite/finders/remote.py
webapp/graphite/finders/utils.py
webapp/graphite/render/datalib.py
webapp/graphite/storage.py
webapp/graphite/tags/localdatabase.py
webapp/graphite/tags/redis.py
webapp/tests/test_tags.py

This PR refactors the redis TagDB implementation to increase performance by evaluating a single "selector" expression and then treating any remaining expressions as filters on that set, rather than evaluating each expression separately and intersecting the results.  This makes a big difference in cases where previously a large number of values would have had to be read from redis and tested in Python (expressions using `!=`, `=~` or `!=~`).
It also refactors the local db implementation to use database joins only for expressions that don't match empty tags, and to use filtering to evaluate any remaining expressions.
It also adds an optimization in the prefetch code so that `extractPathExpressions` isn't called if there are no remote stores enabled.  In a future PR we'll want to add some …

TagDB refactor

---

webapp/graphite/render/evaluator.py
webapp/graphite/render/functions.py
webapp/graphite/render/grammar.py
webapp/tests/test_functions.py

This PR adds support for specifying nodes to be used to match value and total series in calls to `asPercent` using the same logic as in `groupByNodes`.  This allows it to work much more reliably with glob expressions, and doesn't rely on the lists being the same length.  It also makes it much easier to calculate things like disk percentage free/used from raw values.
Usage description and examples are in the updated docblock.  I opted to add the extra params to `asPercent` rather than creating a separate `asPercentByNodes` function both to avoid further bloating the function list, and because I suspect that it will become the preferred way to use `asPercent` when dealing with multiple series.
In order to support the usage where nodes are specified without a `total` series, support has been …

support matching series by node in asPercent

---

webapp/graphite/render/datalib.py
webapp/tests/test_render_datalib.py

This PR updates the code in #771 and incorporates updates from #2051 
In addition, it fixes an issue where consolidating a series by an interval that divides evenly into the number of points in the series results in a None value being appended to the result.
The new tests do highlight the need for support for `xFilesFactor` here, since the final value for some aggregations can be quite nonsensical when there aren't enough points in the interval.

Fix consolidation

---

docs/render_api.rst
webapp/graphite/local_settings.py.example
webapp/graphite/render/datalib.py
webapp/graphite/render/functions.py
webapp/graphite/render/hashing.py
webapp/graphite/render/views.py
webapp/graphite/settings.py
webapp/tests/test_functions.py
webapp/tests/test_render.py
webapp/tests/test_render_datalib.py

This PR adds support for setting the `xFilesFactor` value used when performing consolidations across series or across intervals.
Setting the `xFilesFactor` is accomplished using the new `xFilesFactor()` function which sets the `xFilesFactor` on the series it operates on as well as updating the new `xFilesFactor` setting in the request context (which is used by functions that have to process multiple series, so that they can just use the current setting rather than having to worry about resolving differences in xFilesFactor across the series passed to them).
As part of this update, the handling for all functions that aggregate across series (`sumSeries` & friends) is centralized into a new `aggregate` function which mirrors the previously-added `movingWindow` function used for aggregating …

implement xFilesFactor support, add aggregate function

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This PR defines a new standardized function `aggKey()` for taking a list of nodes and/or tags and producing an identifier for a given series.
This function is used by `aggregate()`, `asPercent()`, `weightedAverage()`, `aliasByNode()`, `mapSeries()`, `groupByNode()`, `groupByNodes()` & `aliasByTags()`, all of which now support specifying nodes and/or tags interchangeably.
After this change, `aliasByTags()` and `aliasByNode()` are identical, though `groupByTags()` still differs from `groupByNodes()` because it return series using "tagged" names rather than flattening them into dot-delimited names.  For that reason it also does not support integer node ids.
There are a few functions that have not been updated because they use node numbers in different ways;  the `*WithWildcards()` functions, …

Support using tags in functions that accept nodes

---

webapp/graphite/render/views.py
webapp/tests/test_render.py

This PR refactors `render/views.py` to break up the monolithic `renderView()` function into a set of helpers for each output format, and to unify handling of response caching and render logging.
It also expands the render test suite to increase coverage for the new helper functions to 100% and cover more of the available query parameters.
Finally, the second commit introduces a change to the consolidation behavior when `maxDataPoints=1` is specified.  Previously this path used the same "nudging" logic as other `maxDataPoints` values, but that would often produce nonsensical results because it would "nudge" out a large number of data points.  With this change there is no longer any "nudging" with `maxDataPoints=1` and all available points are simply consolidated.

Render view refactor & maxDataPoints=1

---

webapp/tests/test_render.py

This PR adds timestamps to CSV requests in the render tests to improve reliability of the tests, since currently they're timing-sensitive.

improve test reliability

---

webapp/graphite/finders/__init__.py
webapp/tests/test_finders.py

to fix https://github.com/graphite-project/graphite-web/issues/2012
remove file extension when getting `base_fs_path `
use `os.sep` to replace `'/'`
rename 
`real_fs_path `to `real_aboslute_path`
`relative_real_fs_path  `to `real_relative_fs_path `

fix for issue 2012

---

docs/tags.rst
webapp/graphite/readers/remote.py
webapp/graphite/settings.py
webapp/graphite/tags/http.py
webapp/tests/test_tags.py

This PR adds a TagDB that forwards all tag-related operations to an HTTP(S) server that implements the graphite-web tagging API.
It's designed to be used as a standard way to integrate with outboard tag databases, or with clustered graphite configurations.
I'm not sure what the best way is to go about writing tests for this, since you really need to have 2 graphite installations running for it to work.  Any suggestions appreciated!
I also fixed a minor bug in the remote reader, which wasn't properly formatting the error log entry if the remote returned a non-200 status code.

HTTP(S) TagDB

---

webapp/graphite/events/views.py
webapp/tests/test_events.py

The changes in #1627 broke support for passing tags as a space-separated string when creating new events.  This PR properly handles tags specified as an array or a space-separate string.
It also improves test coverage, and corrects an exception thrown if no `HTTP_ACCEPT` header is sent to the detail endpoint.

restore support for specifying tags as space-separated list, improve tests

---

webapp/graphite/render/datalib.py
webapp/graphite/storage.py

The new `disabled` flag for finders won't be defined by custom finders that don't extend `BaseFinder`, so we need to provide a default value for `getattr` calls that reference it.

default value for getattr disabled

---

webapp/graphite/local_settings.py.example
webapp/graphite/logger.py
webapp/graphite/settings.py

This PR adds 4 new config settings for the names of the 4 files that graphite-web logs to, and adds code to send these logs to `stderr` instead if those filenames are specified as `-`.
When sending logs to `stderr` the format is modified to make them easier to distinguish, and to support that it removes the (bogus) custom level names that were breaking formatting of warning messages, and updates the rendering and cache loggers to use `INFO` level.

support sending logs to stderr

---

webapp/graphite/render/attime.py
webapp/tests/test_attime.py
webapp/tests/test_render.py

This patch corrects some issues in `parseATTime` when used with the `now` parameter, adds support for times formatted like `6pm` or `10am`, and handles dates like `H:mmYYYYMMDD` properly.
It also expands the test suite to catch a number of edge cases.
This supercedes #2064 and #2067

Improve parseATTime

---

webapp/graphite/render/glyph.py
webapp/tests/test_render.py
webapp/tests/test_render_glyph.py

Display 'No Data' graphs for graphType=pie when there's no data.  Current situation is a failure case.
Also, perform the same defensive tests before attempting to draw a legend with no elements that happens in LineGraph's drawGraph.
Added a few tests to cover this.

Handle no data with graphType=pie

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This PR applies an optimization from `movingWindow` to `linearRegression`, `timeShift` & `timeStack` whereby it uses `requestContext['args'][0]` to get the raw tokens for the first parameter and evaluate them in a modified context, rather than trying to reverse-engineer them from `seriesList[0].pathExpression`.
This results in a speedup when using an expression like `timeShift(sumSeries("test.*"),"10min")` because `seriesList[0].pathExpression` would be `sumSeries(test.1,test.2,test.3,...,test.N)` where `requestContext['args'][0]` will be equivalent to `sumSeries(test.*)`.
For `useSeriesAbove` we use a different approach, building a single `evaluateTarget()` call with a group of new series to query instead of evaluating each one separately.
Right now these don't result in a huge speedup, …

improve effciency of linearRegression, timeShift, timeStack & useSeriesAbove

---

webapp/graphite/render/evaluator.py
webapp/graphite/render/functions.py
webapp/graphite/render/utils.py
webapp/graphite/render/views.py
webapp/tests/test_functions.py

When functions need to perform sub-requests to get data for a time range that's different from the main query (eg `moving*`, `timeShift`, etc) they currently always go through the regular find/read pipeline and can't use the faster prefetch mechanism to optimize those requests (instead potentially making a large number of small requests to the backend servers).
This PR moves the triggering of the prefetch mechanism from `views.py` into `evaluateTarget` and updates it to be able to accept pre-tokenized input, a raw string, or a list of tokens/strings.  All functions now use `evaluateTarget` instead of `evaluateTokens` so that they can take advantage of prefetching.
The special case here is `seriesByTag` which explicitly disables prefetching because the series will already have been …

Use prefetch logic for sub-requests

---

docs/config-local-settings.rst

The filename for the example vhost configuration is "example-graphite-vhost.conf", it is documented correctly once and incorrectly referred to as  "example-graphite-vhosts.conf" once.  Not a huge issue, but it can cause confusion when users copy/paste this name when searching for the file on their filesystem(ie me).

Fix example vhost filename

---

webapp/graphite/readers/utils.py
webapp/graphite/readers/whisper.py
webapp/tests/test_readers_util.py
webapp/tests/test_readers_whisper.py

This follows on from #2081 and simplifies the logic used to pre-aggregate the points from carbon cache before using the specified consolidation function.  It also includes a small optimization to use an array comprehension instead of `append` in a loop to build `consolidated`.
@olevchyk does this make sense to you?

Aggregate points from carbon cache like whisper

---

webapp/graphite/local_settings.py.example
webapp/graphite/settings.py
webapp/graphite/tags/base.py
webapp/graphite/tags/http.py
webapp/graphite/tags/localdatabase.py
webapp/graphite/tags/redis.py
webapp/graphite/tags/utils.py
webapp/graphite/util.py

This PR implements support for caching the results of calls to the TagDB `find_series` function.
It avoids having to re-implement the caching code in each TagDB by updating them to implement `_find_series` and adding a new `find_series` in `BaseTagDB` that handles the caching.  A TagDB may handle caching itself by implementing `find_series` directly (though it will still need to provide an implementation of `_find_series` as well to satisfy the metaclass requirements).
I also refactored the `BaseTagDB` class into its own file, and added support in the `@logtime` decorator for logging time taken for failures (exception raised by function) and for customizing the module name in the log output.
Finally, I added a new setting `TAGDB_CACHE_DURATION` (default to 60s) and added the `TAGDB_*` …

TagDB caching

---

webapp/graphite/render/datalib.py
webapp/tests/test_render_datalib.py

While putting test cases together, I noticed I couldn't get this conditional to be true:
```
if known.name in series_best_nones: 
known_nones = series_best_nones[known.name]
```
I believe there are two issues.
1. The base case for a key not existing in series_best_nones is missing.
2. The declaration of series_best_nones dictionary is inside the loop.
Also added more test cases for _merge_results() and test cases for FetchData().

Fix caching in _merge_results and add tests

---

webapp/graphite/tags/http.py

This PR switches the HTTP TagDB code to use GET for its requests, since currently it sends a POST with the tags expressions in the URL and an empty body.

Use GET for HTTP TagDB findSeries requests

---

docs/config-local-settings.rst
webapp/graphite/settings.py

This is useful if you want to use a custom HTTP header for authentication.
The current code will always append the Djangos `RemoteUserMiddleware`  to `MIDDLEWARE`. Even if you add your own middleware (using Django imports at the bottom of `local_settings.py`), the `RemoteUserMiddleware` will always be executed last and your custom middleware will do nothing.
It's possible to hardcode a full set of middlewares at the bottom of `local_settings.py` (which is what I am doing at the moment), but it's will probably break with future updates.
I also fixed the `REMOTE_USER_BACKEND` documentation which was confusing.

Add REMOTE_USER_MIDDLEWARE configuration option and fix REMOTE_USER_BACKEND documentation

---

webapp/graphite/render/functions.py
webapp/graphite/util.py
webapp/tests/test_util.py

The `hitcount` function creates a `requestContext['startTime']` date that isn't timezone-aware, which can cause problems. This patch updates it to pass the `tzinfo` parameter like `smartSummarize` does.
The `epoch` function fails when passed a naive datetime (without timezone info), this patch updates it to interpret it as a date in the timezone specified in settings.
This patch also adds test for `epoch` and `epoch_to_dt`.

use timezone-aware dates in hitcount, update epoch to handle naive dates

---

docs/tags.rst
webapp/graphite/tags/base.py
webapp/graphite/tags/localdatabase.py
webapp/graphite/tags/urls.py
webapp/graphite/tags/views.py
webapp/tests/test_tags.py

This PR implements a pair of endpoints to be used for providing autocomplete for tags and values based on series matching a given set of tag expressions.
```
/tags/autoComplete/tags?expr=tag1=value1&tagPrefix=tag
/tags/autoComplete/values?expr=tag1=value1&tag=tag2&valuePrefix=value
```
Both urls accept 0 or more `expr` or `expr[]` items and will return at most 100 matches.  `tagPrefix` and `valuePrefix` are both optional.

Auto complete for tags

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py
webapp/tests/test_util.py

This PR adds support for passing an optional `xFilesFactor` parameter to `removeEmptySeries()`, so the user can control the threshold for considering a series to be non-empty.  This can be useful for removing series that have patchy data eg before using a function like `averageSeries()`.
As `removeEmptySeries()` now uses `xffValues()`, the now-unused `safeIsNotEmpty()` function has been removed.
This PR also includes a fix for running tests on hosts that don't provide an ipv6 address for the local interface, as it seems that the latest travis-ci update uses an ipv4-only `lo`.

removeEmptySeries xFilesFactor support

---

webapp/graphite/settings.py

Fixed #2101.
Will link to `latest` if version contains `-dev`.
I also made the URL https.

[Issue #2101] Use WEBAPP_VERSION in documentation link

---

docs/config-carbon.rst

As mentioned in graphite-project/whisper#239 the code supports "week"
as a unit of time, so document it

Document week / w suffix

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

When combining series with different intervals using `normalize`, the number of resulting values may not always be equal.  In the past the consolidating generator worked around this problem by yielding an extra `None` value, but that wasn't a great way to solve the problem.
Now that we require Python 2.7, we can switch from using `izip` to `izip_longest` when combining values from multiple `TimeSeries`, which will pad any short series with `None` to avoid this problem when aggregating series with a different number of values.
In `_summarizeValues` I also made a change to avoid trying to walk past the end of the `datapoints` array if for some reason it still ended up shorter than expected.
Finally, I added some test code to validate functionality with series having differing steps, as the …

Fix issues when combining series with different intervals

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Historically `perSecond` has returned only integer values, which causes problems when dealing with series that have fractional per-second rates.
This PR updates `perSecond` to use float division and return the resulting values rounded to 6 digits (like we do in `exponentialMovingAverage`).
I also corrected some language in the docs, and added a test to verify that `perSecond` now works properly with fractional rates.
I'm not entirely sure why the old code had `+ 1` in the rollover code, possibly it was related to the integer division.  In any case the new code does pass all the old tests without changes (with the `+ 1` in place it would produce fractional results).

update perSecond to return float values

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This is a proposed solution to the issues outlined in #2116 
It standardizes the handling of maxValue and None between `perSecond` and `nonNegativeDerivative` byt adding a new helper function `_nonNegativeDelta` that is used by both functions.
It also adds test to validate that the results are consistent, as well as improving the efficiency of `scaleToSeconds` and rounding its output to 6 significant digits.

[proposal] clean up perSecond and nonNegativeDerivative maxValue and None handling

---

.travis.yml
tox.ini
webapp/graphite/finders/ceres.py
webapp/graphite/finders/remote.py
webapp/graphite/finders/standard.py
webapp/graphite/finders/utils.py
webapp/graphite/local_settings.py.example
webapp/graphite/metrics/views.py
webapp/graphite/settings.py
webapp/graphite/storage.py
webapp/graphite/util.py
webapp/graphite/worker_pool/pool.py
webapp/tests/test_finders.py
webapp/tests/test_finders_remote.py
webapp/tests/test_metrics.py
webapp/tests/test_storage.py
webapp/tests/test_util.py
webapp/tests/test_worker_pool.py

This PR moves all code used for generating `/metrics/index.json` into a new `get_index` function in `STORE` which uses the same worker pool approach as `find` and `fetch`.  It also provides a default implementation of `get_index` in `BaseFinder` so that all existing plugins will now expose their metrics automatically (the default implementation maps `get_index` to a `find_nodes` call with pattern `**`).  Finders are able to override `get_index` to provide their own more efficient implementation, which is what the `standard`, `ceres` & `remote` finders now do.
The only non-BC change introduced is to remove the old `cluster` parameter and behavior from `/metrics/index.json` and replace it with the same `local=1` behavior as `/metrics/find` and `/render`.  This means the following changes: …

Move /metrics/index.json handling into finders & use worker pool

---

webapp/graphite/render/evaluator.py
webapp/graphite/render/functions.py
webapp/graphite/tags/base.py
webapp/graphite/tags/http.py
webapp/graphite/tags/localdatabase.py
webapp/graphite/tags/redis.py
webapp/graphite/tags/views.py
webapp/tests/test_functions.py
webapp/tests/test_tags.py

The tagdb http backend might require the `X-Org-Id` header, this patch passes it through

pass headers to tag db

---

webapp/graphite/storage.py
webapp/graphite/tags/base.py
webapp/graphite/tags/http.py
webapp/graphite/tags/localdatabase.py
webapp/graphite/tags/redis.py
webapp/graphite/tags/utils.py
webapp/graphite/tags/views.py
webapp/tests/test_tags.py
webapp/tests/test_util.py
webapp/tests/test_worker_pool.py

This PR makes a number of updates to the internal TagDB APIs, so I bundled them together to avoid plugin authors having to update multiple times.
The first change is to add a `limit` parameter to the `list_tags`, `get_tag` & `list_values` methods, which allow for better efficiency in the autocomplete case where there is no starting expression because we can push the limit down to the database or out to the remote http tagdb.
The second change standardizes the internal parameter names to keep things clean, though it doesn't change the `tagPrefix` and `valuePrefix` query parameters for auto-complete, since Grafana already uses those.
The last change is a refactor so that the base TagDB uses dependency injection to get the settings, cache & log objects, so that the internal dependencies are …

Tagging updates

---

.travis.yml
docs/config-local-settings.rst
tox.ini
webapp/graphite/finders/remote.py
webapp/graphite/metrics/views.py
webapp/graphite/readers/remote.py
webapp/graphite/render/views.py
webapp/graphite/umsgpack.py
webapp/graphite/util.py
webapp/tests/test_finders_remote.py
webapp/tests/test_metrics.py
webapp/tests/test_readers_remote.py
webapp/tests/test_render.py

This PR adds support for msgpack output for render and find endpoints.  The data returned is almost identical to the pickled data, except that intervals are returned as arrays of `[start, end]` so that we don't require a custom msgpack extension.  msgpack output is enabled using `format=msgpack`.
The PR also add support for using msgpack encoding for intracluster render and find calls, and adds support for specifying per-host options when defining cluster hosts by appending them as query parameters, as well as for specifying the protocol to use (http or https).
Currently supported options are `format` (`pickle` (still the default) or `msgpack`) and `local` (`1` (default) or `0`).  For example, specifying a cluster host of `https://some.host?format=msgpack&local=0` will cause graphite-web …

Msgpack support

---

docs/tags.rst
webapp/graphite/storage.py
webapp/graphite/tags/base.py
webapp/graphite/tags/http.py
webapp/graphite/tags/urls.py
webapp/graphite/tags/views.py
webapp/tests/test_tags.py

This PR adds support for tagging or removing multiple series from the TagDB at once.  The primary purpose is to support batching tag updates in carbon, and I will open a PR there also shortly.
The main addition is the new endpoint `/tags/tagMultiSeries` which accepts multiple `path` (or `path[]`) parameters and returns a list of the canonicalized paths.  I didn't implement it as an extension of `/tags/tagSeries` since that would require the caller to handle different return values for a single series (the path as a string) vs multiple series (a list of paths).
I also added support in `/tags/delSeries` for multiple paths, here there isn't a need for a separate endpoint since it always returns `true`.
While working on this I noticed a ton of repeated boilerplate in `tags/views.py`, so I …

Multi series tag/delete support

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

OverflowError for perSecond was fixed in #2029, but in #2115 OverflowError is back.
There fix of perSecond, scaleToSeconds and updated tests.

Get rid of OverflowError in perSecond and scaleToSeconds

---

webapp/graphite/tags/utils.py
webapp/tests/test_tags.py

This PR changes the behavior of the `TaggedSeries.encode` function to replace `.` characters with `_DOT_` rather than `-` when encoding filenames.  This allows us to implement a more reliable `decode` method, since series will be much less likely to include the string `_DOT_`.  Decode is not yet used, but could be useful if we want to allow the whisper/ceres finders to return more friendly names in their find output.
NB that this is a breaking change to the file naming scheme.

 use _DOT_ to replace literal . in tagged series filenames 

---

webapp/graphite/finders/utils.py
webapp/tests/test_storage.py

Currently if a find query returns nodes that are not `LeafNode` objects then `fetch` will fail when it tries to call `.fetch()` on them.  This can happen if the pattern provided matches a branch node and the finder doesn't respect the `leaves_only` attribute on the `FindQuery` object.
This PR updates `BaseFinder.fetch` to check whether nodes are `LeafNode` objects before calling `.fetch()` on them.

Fix issue when finder doesn't respect FindQuery leaves_only flag

---

webapp/graphite/tags/http.py
webapp/tests/test_tags.py

urllib3 doesn't properly handle field dicts, leading to errors when using the http tagdb,
This PR maps them into lists of `(field, value)` tuples instead, which are properly supported.

fix fields handling in http tagdb

---

.eslintrc.js

Codacy will be the only thing that potentially uses this right now.
This is the first round of adding this in.  Nothing conforms completely to this, but that's to be expected.  It matches mostly what Codacy checks right now anyways.
I chose single quotes over double quotes since that seems to be the most predominant, but we can change that if consensus is another way (double or ignore)

Adding new ESLint config file.

---

webapp/content/js/browser.js
webapp/content/js/completer.js
webapp/content/js/composer.js
webapp/content/js/composer_widgets.js
webapp/content/js/dashboard.js

Most were global variables defined in the templated html files or other included javascript files.
Others needed var/const declarations.
Only ones left are:
```
2703:14  error  'ace' is not defined                                            no-undef
2705:20  error  'require' is not defined                                        no-undef
2802:19  error  'newURL' is not defined                                         no-undef
2803:36  error  'newURL' is not defined                                         no-undef
3333:55  error  'reset_params' is not defined                                   no-undef
```

 Remove most undefined variables issues in javascript files

---

webapp/graphite/finders/remote.py
webapp/graphite/finders/utils.py
webapp/graphite/render/datalib.py
webapp/graphite/render/evaluator.py
webapp/graphite/render/functions.py
webapp/graphite/render/glyph.py
webapp/graphite/render/grammar.py
webapp/graphite/render/views.py
webapp/graphite/storage.py
webapp/graphite/tags/views.py
webapp/graphite/util.py
webapp/tests/test_finders_remote.py
webapp/tests/test_functions.py
webapp/tests/test_readers_remote.py
webapp/tests/test_render.py
webapp/tests/test_storage.py

This PR implements support for distributed tag databases in a clustered graphite scenario, forwarding `seriesByTag` expressions to cluster hosts that support tags.  This will allow tagged graphite to scale out across a cluster horizontally the same way that non-tagged graphite does.
It is currently functional, but needs work on test coverage and cleaning up any rough edges.
The basic concept is that `seriesByTag` handling is moved into the `STORE.fetch()` method, and it can look up per-finder whether the finder supports tags and if so send the `seriesByTag()` expression through to the finder.  For finders that don't support tags the TagDB is used to look up the matching series and the resulting series are fetched.

Tag federation & py3 fixes

---

webapp/tests/test_readers_whisper.py

This PR aims to decrease the random errors we get from the whisper intervals tests.  As far as I can see it's a timing issue making the tests sometimes return a timestamp 1 less than we were expecting, so this just stops treating that as an error.
I'd like to do some work on whisper to make it less sensitive to wall-clock time, but for now this should stop the random annoying test failures.

work around timing issue in whisper reader interval tests

---

docs/releases.rst
docs/releases/1_1_1.rst

I found out that 1.1.0 release is broken for carbon on pypi. Will rename it to 1.1.1 and will hide 1.1.0

Rename release 1.1.0 to 1.1.1

---

.travis.yml
webapp/graphite/finders/remote.py
webapp/graphite/metrics/views.py
webapp/graphite/readers/remote.py
webapp/graphite/render/datalib.py
webapp/graphite/render/views.py
webapp/tests/test_metrics.py
webapp/tests/test_readers_remote.py
webapp/tests/test_render.py

By default `msgpack-python` will decode string values to binary strings under python 3.x, which causes issues when trying to use the decoded dicts.  In addition, non-unicode strings (eg string literals in python 2.x) are encoded as the `bin` type rather than the `str` type.
This PR fixes those issues by ensuring that all strings that we encode are unicode, and that we use the right options when calling msgpack functions.  `umsgpack` already does the right thing, and it ignores the new parameters.
I also added python3.6 with `msgpack-python` to the build matrix, and added some better error handling if the remote render response doesn't contain the items we're looking for.
I opted to use `unicode` vs `u''` for the literals to treat them the same way as we do the string vars, under python 3 …

ensure that msgpack strings are properly encoded and decoded

---

webapp/graphite/app_settings.py

This update ignores the bogus url warnings that are seen with django <1.10 after the routing refactor in #2157 
https://stackoverflow.com/questions/41449814/django-url-warning-urls-w002
It also updates the `INSTALLED_APPS` setting to include `graphite.functions` and sorts the graphite modules in the list.

ignore bogus url warnings, update INSTALLED_APPS

---

webapp/tests/test_readers_multi.py

This PR updates the last remaining place where `interval.end` is compared with a timestamp, which can cause timing-related test failures.

fix interval end test error

---

.travis.yml
tox.ini
webapp/graphite/render/hashing.py
webapp/tests/test_render.py

This PR is an attempt to future-proof the fnv1a_ch hash computation by properly handling multi-byte characters in addition to applying the fix described in graphite-project/carbon#714 and #2165.
The way we use the `fnv32a` hash function is now consistent with other hash functions where any string is encoded into utf-8 before being hashed.  This produces consistent results across python 2.x and 3.x with or without the pyhash library, and should be consistent with any third-party implementations.
I added pyhash to tox and travis, and added a quick test with multibyte characters to verify that the behavior is now consistent (the previous code would just crash and burn with a `UnicodeEncodeError` without pyhash, and produce inconsistent results with pyhash).

Fix hash position computation of fnv1a_ch

---

webapp/graphite/render/hashing.py
webapp/tests/test_render.py

If the fnv1a hash of a given key returns a value less than 0x10000000, then the high and low parts of the hash would be split incorrectly, resulting in a wrongly computed hash position.
This removes the hex formatting and splitting of the fnv1a hash, and just calculates the position using bit manipulation.
Patch taken from graphite-project/carbon#715.

Fix hash position computation of fnv1a_ch.

---

webapp/graphite/render/functions.py

- fix typo in aggregate arg definition (#2169)

[1.1.x] fix typo in aggregate arg definition

---

tox.ini
webapp/tests/README.md

It's been a little while since I wrote some tests and had to remember how to invoke the test harness and verify the test coverage, so I wrote it down.  Wording and everything open for discussion/adjustment and I may not be describing the optimal ways to do any of this.
* Add README for how the Django-based tests are run.
* Also adjust the coverage invocation so that manual runs can pass in specific test classes or test methods to run during debugging/testing.

Add a README and examples for invoking test harness by hand

---

bin/build-index
webapp/graphite/storage.py
webapp/tests/test_storage.py

This PR restores support for the `build-index` command, which now uses `STORE.get_index()` to get the list of defined metrics.
Note that the `--ceres-dir` and `--whisper-dir` args have been removed as they aren't applicable any more.

build-index

---

webapp/graphite/finders/standard.py

This PR addresses some of the issues mentioned in #2183, by reducing the number of system calls that need to be made to traverse the tree.
There are further potential optimizations possible when `pattern` can be expanded into a finite list of potential names, though this PR does not implement those.

improve efficiency of standard finder

---

docs/config-local-settings.rst
webapp/graphite/finders/remote.py
webapp/graphite/local_settings.py.example
webapp/graphite/readers/remote.py
webapp/graphite/settings.py
webapp/graphite/storage.py
webapp/graphite/tags/http.py
webapp/tests/test_finders_remote.py
webapp/tests/test_readers_remote.py
webapp/tests/test_storage.py

This PR renames the old `REMOTE_FIND_TIMEOUT` and `REMOTE_FETCH_TIMEOUT` settings to `FIND_TIMEOUT` and `FETCH_TIMEOUT` to better reflect how they're used in 1.1.x.  Backward compatibility is retained for anyone using the old names in `local_settings.py`.
It also increases the default setting for FETCH_TIMEOUT from 3 to 6 seconds.

Rename timeout settings

---

webapp/graphite/render/datalib.py
webapp/graphite/storage.py
webapp/graphite/tags/base.py

This allows one to set TAGDB to None to disable the
tagging code entirely.
Also catch more errors when trying to parse tags. For example
people using the old syntax for time (time(foo) instead of time("foo"))
would have `[]` as a name which would break the match

Make it possible to fully disable tags

---

webapp/graphite/metrics/views.py
webapp/graphite/render/datalib.py
webapp/graphite/settings.py
webapp/graphite/storage.py
webapp/graphite/tags/base.py
webapp/graphite/worker_pool/pool.py
webapp/tests/test_storage.py
webapp/tests/test_worker_pool.py

- Make it possible to fully disable tags (#2206)
- Add support for leavesOnly in /metrics/find (#2181)
- storage: cleanup job pool usage (#2181)

[1.1.x] Make it possible to fully disable tags | Add support for leavesOnly in /metrics/find | storage: cleanup job pool usage

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

`groupByNode(perSecond(foo.bar,1), 1)` would display `bar,1)` instead of `bar`
before these change. I suspect that we might want that for all calls of `aggKey()`
Current workaround is to aliasByNode() before groupping.

functions: fix groupByNode() output

---

docs/config-carbon.rst
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

- functions: fix groupByNode() ouput (and others) (#2213)
- Update config-carbon.rst (#2215)
- Update config-carbon.rst (#2215)
- Update config-carbon.rst (#2215)

[1.1.x] functions: fix groupByNode() ouput (and others) | Update config-carbon.rst | Update config-carbon.rst | Update config-carbon.rst

---

webapp/graphite/finders/utils.py
webapp/tests/test_finders.py

- handle case when node.fetch returns None (#2223)

[1.1.x] handle case when node.fetch returns None

---

webapp/graphite/render/functions.py

This PR adds the possibility to specify the seasonality when asking for a Holt-Winters prediction.
Before, the seasonality was to 1 day by default.

Add seasonality parameter for holt-winters functions

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This PR adds an optional `keepStep` parameter to `aggregateLine` to support the use-case described in #2232

add optional keepStep parameter to aggregateLine

---

webapp/graphite/finders/ceres.py
webapp/graphite/finders/standard.py
webapp/graphite/tags/utils.py
webapp/tests/test_finders.py

This is the graphite side of graphite-project/carbon#743, adding support for graphite-web to read tagged metrics stored in hashed files.  The way it's implemented here graphite-web will look for both variants so there isn't a need for a configuration option in graphite-web.
This branch also includes an optimization to avoid scanning whisper folder to resolve brace expressions like `{foo,bar}`, which should provide a modest performance increase.
I still need to do some real-world testing on this.

Support for storing tagged series in hashed filenames

---

webapp/graphite/finders/remote.py
webapp/graphite/tags/views.py
webapp/tests/test_finders_remote.py

This PR makes the `tags/autoComplete/tags` and `tags/autoComplete/values` API calls work properly in a clustered configuration of graphite-web. It adds the `localOnly` query parameter as needed in order to avoid an infinite recursion of API calls across the cluster, similarly to `/metrics/find`.
Fixes https://github.com/graphite-project/graphite-web/issues/2243
Follows https://github.com/graphite-project/graphite-web/pull/2128

w/g/f/remote.py: add missing local field to auto_complete_{tags,values}

---

webapp/graphite/render/datalib.py
webapp/graphite/render/views.py

support specifying noNullPoints and maxDataPoints together

---

setup.py

Fixing https://github.com/graphite-project/graphite-web/issues/2193
Also, upgrade manual for next release should include instructions to remove all `/opt/graphite/storage` entries from `/opt/graphite/lib/graphite-web-x.x.x-pyx.x.egg-info/installed-files.txt` file before the upgrade.

Adding dummy.txt to storage dirs

---

webapp/graphite/render/functions.py

I was seeing errors due to code like safeMax(series) > 0, where safeMax
returned None.

graphite functions: handle max on empty sequences better

---

docs/releases.rst
docs/releases/1_1_3.rst

- Releae notes for 1.1.3 (#2272)
- Update 1_1_3.rst (#2272)

[1.1.x] Releae notes for 1.1.3 | Update 1_1_3.rst

---

webapp/graphite/account/ldapBackend.py

LDAP return bytes type variable: b'example@domain.com', which results this:
File "/opt/graphite/webapp/graphite/account/ldapBackend.py", line 54, in authenticate
user = User.objects.get(username=username)
File "/opt/graphite/lib/python3.4/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/opt/graphite/lib/python3.4/site-packages/django/db/models/query.py", line 380, in get
self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
During handling of the above exception, another exception occurred:
File "/opt/graphite/lib/python3.4/site-packages/django/core/handlers/exception.py", line 41, …

Fix LDAP email address

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This PR aims to improve the performance of `keepLastValue` by avoiding overwriting every point unnecessarily, and avoiding the array lookup & calculation for every point backfilled.

improve performance of keepLastValue

---

webapp/graphite/render/functions.py

If a user specifies the `n` parameter to any of the `highest*` or `lowest*` functions as a numeric string `'20'` rather than a bare number `20` they will receive the error `TypeError: slice indices must be integers or None or have an __index__ method` since the string value can't be used to slice the list of series.
This PR implements a very simple fix by casting the provided value to an integer before using it to slice the series list, which will avoid this issue.
Longer-term a better solution to this kind of problem is likely going to be to use the function definition to perform validation and normalization in `evaluateTokens` before calling the actual function.

handle highest/lowest thresholds specified as numeric strings

---

webapp/graphite/carbonlink.py

This is needed for python3 to treat it as bytes. For py2 bytes is
the same as str so does not change the behavior.
fixes: https://github.com/graphite-project/carbon/issues/756

carbonlink: set the type of the recv buffer explicitly to bytes

---

webapp/content/js/composer.js
webapp/graphite/templates/composer.html

Adds forward / backward functionality too the composer for easier navigation. Also, the url updates whenever the composer is modified, allowing the (long) url to be copy-pasted from the address bar.
Test locally in Firefox, Chrome, and Safari.

Allow history tracking in composer

---

webapp/graphite/finders/__init__.py
webapp/tests/test_finders.py

Currently, a FindQuery for `{foo,bar}.{foz,baz}` will search on a ceres database for `foo.{foz,baz}` and `bar.{foz,baz}`; it's expanding only the first match.
This PR contains a test for triggering this issue and a fix for this issue.

Better support for variant in ceres

---

requirements.txt

This is a temporary fix to use an older version

Latest whitenoise is not supported by graphite

---

webapp/graphite/finders/__init__.py
webapp/tests/test_finders.py

Take 4, last try for now.  I was informed that I needed an active Travis CI account w/ the same username as my GitHub account for the Travis CI PR build to occur successfully. I'm skeptical, but I've linked my accounts via OAuth and will see if the results differ afterward now.

Fix get_real_metric_path for paths where an intermediate directory is a symlink 

---

requirements.txt
webapp/graphite/app_settings.py
webapp/graphite/wsgi.py

https://github.com/graphite-project/graphite-web/issues/2332
https://github.com/graphite-project/graphite-web/pull/2331
This should fix support for WhiteNoise 4. Note that you'll need Django > 1.10 (I think).
I've only tested with gunicorn. Had to rerun manage.py collectstatic.

Add support for WhiteNoise 4

---

docs/releases.rst
docs/releases/1_1_4.rst

- Release notes 1.1.4 (#2348)
- Grammar fixes (#2348)

[1.1.x] Release notes 1.1.4 | Grammar fixes

---

webapp/graphite/finders/remote.py
webapp/tests/test_finders_remote.py

As generators are lazy, in context of pool exceution it will return
immediately and exceptions can not be caught as expected.

Do not use generator for jobs need to be run in pool

---

webapp/content/js/dashboard.js

`Ext.Msg.alert` doesn't automatically escape HTML special characters in the message, which can lead to display issues and could be a potential area for XSS.
The new `htmlEncode` function added errs on the side of caution by encoding all characters other than alphanumeric and space.

html-encode text passed to Ext.Msg

---

conf/graphite.wsgi.example
docs/config-local-settings.rst
webapp/graphite/settings.py
webapp/graphite/wsgi.py
webapp/manage.py

Alternate PR version for #2329 without architectural changes.
The first version is #2330

Multi-instance settings support [light version]

---

docs/feeding-carbon.rst

There is no ``-q0`` parameter on OpenBSD, being ``-N`` the correct one. The same parameter applies to FreeBSD.

Update FreeBSD/OpenBSD netcat switch

---

webapp/graphite/tags/localdatabase.py

This PR updates the local (mysql, postgres, sqlite) tagdb to use the hash of the series when locating records, which provides a significant performance boost by supporting use of the unique index on `tags_series.hash`.

Increase performance of localdatabase tag db

---

webapp/graphite/finders/remote.py
webapp/graphite/readers/remote.py
webapp/tests/test_finders_remote.py
webapp/tests/test_readers_remote.py

This addresses the issue outlined in #2352 by moving the `deserialize` functions into the remote finder and using them in `find_nodes`.
While this code passes all tests I have not actually tried it yet and would appreciate feedback from anyone who has time to experiment with it.

move deserialize into remote finder

---

webapp/content/js/dashboard.js

PR #2295 broke the Completer in Dashboard.  Default value for query for the past 7+ years has been ''.  Change to be '\*' and override input of '' to be '\*' where I found them.
This fixes for my minimal testing of master.  It's possible there are other places that will need to be corrected.

Fix Dashboard Completer UI to work with changes to /metrics/find

---

requirements.txt

Pinning whitenoise to 2.x for Django 1.4

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

It works in a way similar to maxValue: when the counter wraps, instead of
producing a null value, it computes the difference assuming the counter wrapped
to minValue.
See also #2374

Add a minValue option to nonNegativeDerivative and perSecond

---

webapp/content/js/dashboard.js
webapp/graphite/templates/dashboard.html

I configure graphite-web with `URL_PREFIX = "/graphite"` and these icon urls ended up wrong. This seems to fix it. All other icons in the dashboard and composer seem to be working. But maybe there's an even more correct way, related to the "static" template function? Should it be saved to a variable name like the others here:
https://github.com/graphite-project/graphite-web/blob/1.1.5/webapp/graphite/templates/dashboard.html#L27
EDIT: I went ahead and re-did this the global var way
----
for reference where this is:
before:
after:

fix dashboard graph metric list icon paths with URL_PREFIX

---

docs/config-database-setup.rst
docs/config-local-settings.rst
docs/releases/1_1_1.rst

... and --run-syncdb should no longer be needed.
Initial migrations were created for all models just before 1.1.0
in d1912d4bc0f0. Prior to that, some models did not have any
migrations (and no initial migration), so --run-syncdb was needed
to create tables for them. But now that they have initial migrations,
those migrations run because django knows they have never been
applied, and they fail because the tables already exist. The
--fake-initial option is designed for this situation: it considers
initial migrations already applied if the tables already exist.
fixes #2412 
replaces #2126 
conflicts with #2409 and this is a tiny change so I'd be fine with rebasing this after that lands

docs: for sql db migration to 1.1 recommend --fake-initial

---

docs/tags.rst
webapp/graphite/tags/utils.py

Defining which characters are allowed, and how to query for values containing quotes.
If you agree with the rules defined in this change, then I can also add an according validator to the TagDB

add tag formatting docs

---

webapp/content/js/dashboard.js

This never worked right, but the backend dealt with it until recent changes.
This only happens when the dashboard template is loaded directly from the URL

Fix dashboard template loading from URL

---

webapp/content/js/dashboard.js

This makes these url settings match the others in dashboard.js like in PR #797
I don't run on a different baseUrl, but I believe these should match the others.

Dashboard render urls missing document.body.dataset.baseUrl

---

webapp/graphite/carbonlink.py
webapp/graphite/util.py

- Use `socket.create_connection` instead of `socket.connect`.
- Parse host strings properly - using slightly modified `util.parseDestination(s)` functions from *Carbon* project.

Accept IPv6 addresses in CARBONLINK_HOSTS

---

webapp/graphite/render/functions.py

Copy requestContext() and empty prefetch, so we don't override prior fetched data in functions that invoke evaluateToken directly.
Deals with the issues found in #2449

Copy requestContext() and empty prefetch

---

.travis.yml
requirements.txt
setup.py
tox.ini
webapp/graphite/app_settings.py

Adds "django.contrib.messages" to INSTALLED_APPS in local_settings.py for Django22 compatibility.
Adds Django 2.2 to testing, removes Django 1.8, 2.0 and Python 3.4 from testing (EOL).

Django22 compatibility

---

docs/client-apis.rst

This PR fixes a broken link to `structured_metrics` in doc.

Fix a broken link to structured_metrics in doc

---

docs/install.rst

I've encountered issues with current code snippet on some instances of centos, which can is fixed by adding extra spaces before \ signs.

added space before \

---

docs/tools.rst

netdata is a project missing from this list. I hope people can benefit from having it linked here.

docs: add netdata to 'tools that work with graphite'

---

webapp/graphite/render/functions.py

This should fix the validation not being aware of legal aliases.
fix #2494
@DanCech will this break anything else that relies on `.params` ? i see this property is used in quite many places but didn't investigate them all

fix functions that aggregate to include the aliases in their params

---

docs/requirements.txt
tox.ini

According to https://www.djangoproject.com/download/ 1.11 is single 1.x supported version now.
According to https://github.com/graphite-project/graphite-web/network/alert/docs/requirements.txt/django/open versions <1.11.19 vulnerable to CVE-2019-6975 and CVE-2019-3498

Upgrading minimal Django version

---

docs/install.rst
docs/releases.rst
docs/releases/1_1_6.rst

- Prepare documentation for 1.1.6 release (#2504)
- More changes (#2504)
- Amended security issue description (#2504)

[1.1.x] Prepare documentation for 1.1.6 release (#2504) | More changes (#2504) | Amended security issue description (#2504)

---

webapp/graphite/render/evaluator.py

Since Graphite 1.1.6 we get a lot of failed parameter validation errors (not sure why but this is irrelevant here). In any case, although `ENFORCE_INPUT_VALIDATION` is disabled (by default), the code from #2467 logs the error, and while doing so produces an `AttributeError` because there is no `message` field on the exception object. This of course lets the request fail and means that `ENFORCE_INPUT_VALIDATION=False` is currently useless.
The fix just uses `str(e)` instead of `str(e.message)`, I tested on Python 2.7 and 3.6 that it returns the desired string.
With this fix, the problematic requests are processed successfully and the expected warning is logged.
Please backport this to the next 1.1.x release (and I guess it would make sense to make a new release relatively soon because of …

Fix AttributeError if parameter validation fails

---

webapp/graphite/functions/__init__.py
webapp/graphite/functions/aggfuncs.py
webapp/graphite/functions/params.py
webapp/graphite/functions/safe.py
webapp/graphite/render/functions.py
webapp/tests/test_functions.py
webapp/tests/test_params.py

this relaxes the input validation because we have seen issues where queries using deprecated aggregation functions have been rejected (f.e. `sumSeries`). We want these deprecated functions to still be accepted, while logging a warning that a deprecated function has been used.
#2508

relax enforcement of options sets in validation

---

webapp/graphite/functions/params.py
webapp/graphite/render/functions.py

This re-allows the use of series functions as aggregation functions when input validation is enabled.
It tries to detect whether a series func can be used as an aggregation func based on its parameters. that way a lot of series funcs which would never work as aggregations funcs can already be ruled out by the input validation layer, preventing an exception.
Example:
Using the series func `weightedAverage` with `groupByNodes()` blows up because `weightedAverage` requires more parameters than only a list of series:
```
$ curl 'http://localhost:8000/render?target=groupByNodes(some.id.of.a.metric.*,"weightedAverage",4)'
...
File &quot;/home/replay/go/src/github.com/graphite-project/graphite-web/webapp/graphite/render/functions.py&quot;, line 4888, in groupByNodes
metaSeries[key] = …
```

introduce paramtype for agg or series func

---

.travis.yml

xenial and "sudo=true" are standard now
(https://docs.travis-ci.com/user/reference/linux/)
python-3.8 has been released, so "-dev" can be removed
reduce shell quoting complexity by avoiding non-posix expressions

simplify travis-ci config

---

webapp/graphite/functions/params.py
webapp/graphite/render/functions.py
webapp/tests/test_params.py

This explicitly marks every series processing function which may also be used as an aggregator callback by the `groupBy*` functions as such. Every series processing function which has not been marked is considered as not a valid aggregator by the input validation.

Mark series functions to use as aggregators

---

.travis.yml
requirements.txt
setup.cfg
setup.py
tox.ini
webapp/graphite/account/views.py
webapp/graphite/browser/views.py
webapp/graphite/composer/views.py
webapp/graphite/dashboard/views.py
webapp/graphite/events/models.py
webapp/graphite/events/views.py
webapp/graphite/templates/browserHeader.html
webapp/graphite/templates/composer.html
webapp/graphite/templates/dashboard.html
webapp/graphite/templates/event.html
webapp/graphite/templates/events.html
webapp/graphite/version/views.py
webapp/tests/test_render.py

Changes render_to_response() to response().
Changes load staticfiles to load static in templates.
Django 3 sets the private header when setting no-cache headers. Adjusted tests to
reflect this.
Monkeypatched django.utils.enocoding.python2_unicode_compatible so that django-tagging
can continue to function. Django-tagging is dead, it should be replaced with django-taggit
or the graphite events functionality should be removed in favor of Graphana annotations.
Updates travis and tox to test currently maintained Django versions.

Django 3.0 compatibility

---

webapp/graphite/render/functions.py

sets parameter type of functions which represent a data point value from
`integer` to `float` if they were `integer` before. in cases where the
documentation says that the type is `integer` it updates it to `constant`
(`float` or `integer`).
in cases where a parameter represents a percentile this also sets it to
`float`, previously most of them were set to `integer`.
also changes first parameter of `useSeries()` from `string` to `float`,
because I think it should be.
fixes: #2511

fix function parameter types

---

webapp/graphite/functions/params.py
webapp/graphite/render/functions.py
webapp/tests/test_params.py

Introduces new parameter type `intOrInf`. This is necessary because two functions `keepLastValue()` and `interpolate()` have a parameter `limit` which may be an `int` or `inf` but not a numeric `float` value. Unfortunately, in Python, `inf` is a valid `float` but not a valid `int`. So the new type `intOrInf` enforces specifically that a given value is `int` or the float value `inf`, but not any other `float` value.

Parameter type int or inf

---

webapp/graphite/render/evaluator.py
webapp/graphite/render/grammar.py
webapp/tests/test_render.py

Currently unquoted `inf` values are not interpreted, so they get passed into the functions as `[]` (empty list of series). This is an issue because some examples (https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.interpolate / https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.keepLastValue) show an unquoted value `inf` as default. 
These defaults work fine if the value isn't specified, but we've seen cases where users then explicitly specified `limit=inf` like the default value in the docs, which was not interpreted correctly. 
This adds the interpretation of the unquoted `inf` values into `float(inf)`

Interpret inf

---

webapp/graphite/functions/params.py
webapp/graphite/render/evaluator.py

with this change the error message includes useful hints regarding what
the type of a given invalid value is.
F.e. previously a message talking about an `int(1)` value would have been
the same as a message talking about a `str('1')`, but now they are
differentiable because `repr()` indicates the type
These are the log statements resulting from the query `target=scale(a.b.c,"0.123")` (the second parameter is supposed to be a float).
```
2020-02-20,20:03:36.090 :: Received invalid parameters (Invalid float value specified for function "scale" parameter "factor": 0.123): scale ([Time
Series(name=a.b.c, start=1582229014, end=1582229017, step=1, valuesPerPoint=1, consolidationFunc=average, xFilesFactor=0.0)], 0.123)
2020-02-20,20:04:08.945 :: Received invalid parameters (Invalid "float" value …
```

better error messages with type indications

---

webapp/graphite/functions/params.py
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

In the case of the function `asPercent()` we can't use the input validation to validate the value of the parameter `total` because depending the values given in other parameters it may or may not have different types. So instead we just accept any type for `total` and then ensure that the function `asPercent()` raises the correct exception `InputParameterError` if an invalid parameter has been given to prevent exceptions leading to 5xx due to bad input (it already does that without changes).
Fixes #2541

fixes #2541

---

webapp/graphite/errors.py
webapp/graphite/metrics/views.py
webapp/graphite/render/views.py
webapp/graphite/storage.py
webapp/tests/test_metrics.py

Handling various cases of bad input in the `/metrics/find` and `/render` routes and replying with `4xx` instead of `5xx`.
Before merging, there's one thing i'm uncertain about... should the second part of this `if` condition actually be checking `queryParams['until']` or is this really supposed to check `queryParams['from']`? (looks like a bug to me) https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/metrics/views.py#L80
For now I've left the logic as it currently is, but if that's a bug I can push another commit into this PR to fix it, since I'm already changing a lot of lines in that area.

handle exceptions if params cannot be type converted

---

webapp/graphite/functions/params.py
webapp/tests/test_params.py

Found this issue because a user was querying `target=summarize(<metrics>,"15min")`, without specifying the `func` parameter. By default the `func` parameter is `sum`, but the validator threw an exception because `None` is not a valid value for `func`.
The first commit adds a test to illustrate the problem, the second fixes it and makes the test passes.

Fix validator when default value is used

---

webapp/graphite/render/datalib.py
webapp/graphite/render/functions.py
webapp/tests/test_render_datalib.py

it's confusing that most of the functions accepted by `consolidateBy` use a short form like `min`/`max`/`avg_zero`, but `average` needs to be spelled out because `avg` is not accepted.

make consolidation func `avg` alias for average

---

contrib/memcache_whisper.py
setup.cfg
webapp/graphite/logger.py
webapp/graphite/render/glyph.py
webapp/graphite/storage.py
webapp/tests/test_attime.py
webapp/tests/test_dashboard.py
webapp/tests/test_functions.py
webapp/tests/test_metrics.py
webapp/tests/test_render_datalib.py
webapp/tests/test_util.py
webapp/tests/test_whitelist.py

if you have a preference do these fixups a different way, please feel free to comment :)
In some cases I commented out a line, because it was part of the pattern of every test in the series, but unused in one or two tests, or in one case because there were a bunch of other commented out lines further down which referenced it. I could alternatively "delete them all".

flake8: re-enable F841 (local variable assigned but not used)

---

webapp/graphite/render/evaluator.py
webapp/graphite/render/views.py
webapp/graphite/settings.py
webapp/graphite/storage.py
webapp/tests/test_render.py

This PR adds a bit more context to the log messages which are talking about invalid query parameters, if possible. 
When Grafana issues queries from dashboards it adds the org/dashboard/panel id into the headers, with this PR we're extracting those headers if they're present and add them to the log statement. This makes it much easier to go from an error which talks about a bad query to the dashboard & panel where the query came from, because otherwise making that association can be quite hard. 
I hope that's not too Grafana specific to merge it into Graphite, what do you think @deniszh ? I believe that a large number of Graphite users are probably using Grafana for querying, so it would benefit them all. And for those who don't use Grafana nothing changes.
This is an example log …

log grafana dashboard/panel id headers

---

webapp/graphite/render/functions.py

I've seen users using `scaleToSeconds()` with float values as the `seconds` parameter. I think this appears to be a valid use case

Allow floats in scaleToSeconds()

---

docs/releases.rst
docs/releases/1_1_7.rst

- Adding release 1.1.7 (#2562)
- Moving release date (#2562)
- adding latest changes (#2562)

[1.1.x] Adding release 1.1.7 (#2562) | Moving release date (#2562) | adding latest changes (#2562)

---

webapp/graphite/render/datalib.py
webapp/graphite/render/views.py

fixes #2571 by ensuring that all tag values are set as strings.  This fixes a number of places that numeric values could have caused issues.

ensure that all tag values are strings

---

webapp/graphite/functions/params.py
webapp/graphite/render/attime.py
webapp/graphite/render/evaluator.py
webapp/tests/test_params.py

We've seen many cases where users make understandable mistakes, such as specifying boolean parameters as string (`'true'`) or specifying the `inf` value as a string (`'inf'`). 
Now the input validation doesn't only check whether the input is valid, but if possible it also does a type cast of the given parameters. All the validators are now either returning a value of the correct type or raise an exception.

Attempt to convert parameter types in validator

---

webapp/graphite/render/functions.py

this is only to be backwards compatible and not reject old queries. the function code is logging a warning when a boolean value is passed as `alignTo`

accept deprecated params for bc

---

webapp/graphite/render/glyph.py

fixes #1309
which points out that 08be1ba8a465 added this
odd out-of-bounds "header" just for svg metadata

render: only encodeHeader() for svg output

---

webapp/graphite/render/functions.py

we have customer using `asPercent` as an aggregator and that seems to be working, so we should allow it to be used as aggregator in the input parameter validation.

asPercent may be used as an aggregator

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

The documentation specifies the function signature as `groupByNodes(seriesList, callback, *nodes)` in https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.groupByNodes so according to regex logic * would allow 0 instances of nodes. I've seen some users submitting queries like:
```
groupByNodes(<some metrics>, 'average')
```
so basically they're abusing `groupByNodes()` to do `averageSeries()`, which is weird but it works and the docs are not clearly saying that it shouldn't work.

Make nodes in group by nodes optional

---

webapp/graphite/render/functions.py

This function is a helper for linearRegresstion() and doesn't even return a series.
Fixes: https://github.com/graphite-project/graphite-web/issues/2601

privatize linearRegressionAnalysis so it will not show in documentation

---

webapp/content/js/composer_widgets.js
webapp/content/js/dashboard.js
webapp/graphite/browser/views.py

saved graphs targets were html-escaped in the json response
to fix an XSS vulnerability in graphite-project/graphite-web#1662
... but that was not really the right place to escape the graph targets,
it broke targets using quotes: #1801 #2334
so effectively revert the original fix, and instead html-escape the
targets just before rendering them in the GraphDataWindow Ext.ListView
-----
TODO:

fix composer saved graphs target escaping

---

webapp/content/js/dashboard.js

Firefox does not seem to trigger the 'keypress' or 'keyspecial' events for the backspace key, all seems to work correctly with the 'keydown' event. (Chrome does seem to trigger 'keyspecial' for the backspace key.)
Apparently 'keypress' is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event and 'keyspecial' does not seem to be documented, while 'keydown' is well supported: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event
Looking just above in the code we can see that backspace is intended to trigger completion:
```js
function completerKeyPress(thisField, e) {
var charCode = e.getCharCode();
if (charCode == 8 ||  //backspace
charCode >= 46 || //delete and all printables
charCode == 36 || //home
charCode == 35) { //end …
```

fix dashboard metric completion on backspace in Firefox

---

webapp/graphite/functions/params.py

it only checked whether a given value can be converted into a list, it now requires the value to be a list of TimeSeries elements. similarly, the type TimeSeriesLists requires the value to be a list of lists of TimeSeries elements.

seriesList type validation was too permissive

---

requirements.txt

Whitenoise starting at 5.0.0 (10/12/2019) does not support python2.7 anymore and fails building. Locking to latest version that supports python2.7
https://pypi.org/project/whitenoise/5.0/

Lock whitenoise dependency version

---

webapp/graphite/render/functions.py

the current docs are very confusing because:
* the terminology of "wildcards" makes people think it adds wildcards to
the query patterns, and thus may cause additional series to be looked up,
whereas this does not happen.
* the documentation did not describe the relation between "adding
wildcards" and calling sumSeries, averageSeries, etc.
Clarify that we form buckets and call the function on each
bucket.
Also, the example for averageSeriesWithWildcards was effectively
incorrect.

fix & improve docs for *WithWildcards functions

---

webapp/graphite/functions/views.py
webapp/graphite/render/views.py
webapp/graphite/util.py

Infinity is not valid json for browsers or nodejs, but 1e9999 seems to work (already used by render endpoint)
fixes #2609
(in the same hacky way as the render endpoint handles this issue, which is not 100% robust, but may be close enough, see #2610)

functions view: replace Infinity in json response

---

docs/install-synthesize.rst

I've forked the synthesize script in order to make it able to install Graphite and Grafana automatically on CentOS distributions. The installation is already completely functional. It would be really fine to provide this new script to all the community to make their lifes easier.

REsynthesize: New script forked from Synthesize to install Graphite on CentOS

---

docs/config-webapp.rst

The Nginx config block had the correct alias to `webapp/content/`, but
it looks like the Apache example config was not updated.
We were updating from an old version, and found this bug in the docs. We just happened to search through and found the correct alias in the nginx example config block:
https://github.com/graphite-project/graphite-web/blame/master/docs/config-webapp.rst#L79
This is a very easy fix, and hopefully helps someone else out too.
CC @andyg0808

Patch /static/ directory in Apache docs

---

requirements.txt
webapp/graphite/local_settings.py.example
webapp/graphite/metrics/views.py
webapp/graphite/render/grammar_unsafe.py
webapp/graphite/settings.py

Backport unicode fix from https://github.com/piotr1212/graphite-web/c…ommit/17e23efecb6cb40059264fabd3ea36718065176e
Fixing #2641

Backport unicode fix from piotr1212@17e23ef 

---

webapp/content/js/composer_widgets.js
webapp/graphite/render/functions.py
webapp/tests/test_functions.py

Closes: #2645  see for more information. 
Decided to use `aggregate()` as base function when implementing `diffSeriesLists(), sumSeriesLists(), multiplySeriesLists()` as aliases using `aggregateSeriesLists()`. 
Side effect of course is that other functions that are supported by `aggregate()` are also supported by `aggregateSeriesLists()`.

Add aggregateSeriesLists() and aliases for diffSeriesLists(), sumSeriesLists(), multiplySeriesLists()

---

webapp/graphite/render/functions.py

Backport from master. Fixes https://github.com/graphite-project/graphite-web/issues/788. 
Return empty result list for empty series in movingMedian and movingAverage functions.

return empty result list for empty series

---

webapp/graphite/util.py
webapp/tests/test_util.py

should fix #2652, replacing PR #2653

utf-8 fix in unpickle 

---

webapp/graphite/finders/__init__.py
webapp/tests/test_finders.py

Fixes grafana/grafana#5936, grafana/grafana#11274, and #2154
Adding test to PR #2655 
Before 0.9.16 `foo.{bar}.baz` was matching to `foo.bar.baz`, but 0.9.16 breaks that. This update fixes it.

Fix expand braces

---

webapp/graphite/render/functions.py
webapp/graphite/settings.py

When not all data has been loaded in yet for the current minute, the right hand side of a sum can dip which causes some observers heartburn.
Optionally allow a feature that will trim the most recent datapoints if not all of them exist within aggregate().

Optionally resolve right hand dip in sums because of lack of current minute in caches

---

docs/install-pip.rst

Paths in commands specified /var/lib but description specified /usr/share. Makes the command consistent with the description, unless I'm missing something special about /var/lib and the installation procedure.

Fix paths not matching description

---

webapp/graphite/errors.py
webapp/graphite/render/evaluator.py
webapp/graphite/render/views.py
webapp/tests/test_errors.py
webapp/tests/test_functions.py
webapp/tests/test_metrics.py
webapp/tests/test_render.py

This refactors the generation of the log message describing invalid input parameters and moves it into the `InputParameterError` Exception. It makes more sense to have it there, as this exception may be raised and handled in multiple different places. Now the exception can return a useful description of itself based on the context that has been set on it.
It also creates a `targetContext` which gets passed through to other functions via the `requestContext`. This is necessary to make the original raw target string available everywhere where we might want to log an error due to a bad target specification.

Better logs on invalid input

---

webapp/graphite/intervals.py

* removes `__slots__` definition from `Interval` and `IntervalSet`
It took me a minute to figure this one out. So, the original code uses "old style" classes which means that the `__slots__` definition is a noop on python2, but on python3 you automatically get new style classes. Really this should be updated to use "new style" classes, but that would suddenly create compatibility issues between older versions of graphite-web AND also software such as carbonapi which works by mimicking the existing graphite-web behavior. By removing the `__slots__` we get identical behavior on python2 and python3 which is a vanilla unslotted class instance that unpickles fine in both pyhton2 and python3 and works with carbonapi too.

Resolves #2692 can't unpickle Interval/IntervalSet

---

docs/install.rst
docs/requirements.txt
requirements.txt
setup.cfg
setup.py
tox.ini

Depend on third-party scandir only for Python < 3.5

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This is the quick fix from the discussion in #2632 
fixes #2632

fix shifting of moving* datapoints by one step into the future

---

requirements.txt
tox.ini

Pyparsing v3 was recently released, breaking compatibility of graphite-web for usage as Grafana data source. This was observed in Grafana v6.7.x and v8.0.3.
Until compatibility with pyparsing v3 is implemented, this change prevents breaking future deployments of graphite-web as grafana datasource.

Fix dependency issue for usage as Grafana data source.

---

docs/tools.rst

The repo was moved into the `grafana` github org.

Correct carbon-relay-ng url

---

requirements.txt
tox.ini
webapp/graphite/render/evaluator.py
webapp/graphite/render/grammar_unsafe.py

Addresses issue raised in https://github.com/graphite-project/graphite-web/issues/2726 plus one other compatibility issue I came across with a failing piped query test.
I've checked that tests pass but haven't tested this in a live environment. Is it worth adding something to the tox matrix to check multiple pyparsing versions? It's been a while since I've used tox, so I left this part out as I'm not setup to test it properly.

Fix pyparsing > 3.0 compatibility issue.

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py

This implements functions to upper/lower case metric names, or single letters of metric names. We've had users asking for this and I thought this might be useful to other people too.
If this gets accepted I should probably update the example custom function: https://graphite.readthedocs.io/en/latest/functions.html#function-plugins

Implement upper lower case functions

---

docs/config-webapp.rst

- [Fixing typo in documentation (apache) (#2777)](https://github.com/graphite-project/graphite-web/pull/2777)

[1.1.x] Fixing typo in documentation (apache) (#2777)

---

webapp/graphite/render/functions.py

This will backport the following commits from `refs/heads/master` to `1.1.x`:
- [Remove old comment (#2781)](https://github.com/graphite-project/graphite-web/pull/2781)

[1.1.x] Remove old comment (#2781)

---

webapp/graphite/errors.py
webapp/tests/base.py
webapp/tests/test_xss.py

- [Sanitize error output for prevent XSS security issues (#2782)](https://github.com/graphite-project/graphite-web/pull/2782)

[1.1.x] Sanitize error output for prevent XSS security issues (#2782)

---

webapp/graphite/render/functions.py

- [Avoid infinite loop on summarize() (#2784)](https://github.com/graphite-project/graphite-web/pull/2784)

[1.1.x] Avoid infinite loop on summarize() (#2784)

---

webapp/graphite/render/functions.py

- [Fix issue with too small season length (#2780) (#2787)](https://github.com/graphite-project/graphite-web/pull/2787)

[1.1.x] Fix issue with too small season length (#2780) (#2787)

---

webapp/graphite/render/functions.py
webapp/tests/test_functions.py
webapp/tests/test_readers_multi.py

- [Сheck applyByNode nodeNum arg (#2792)](https://github.com/graphite-project/graphite-web/pull/2792)

[1.1.x] Сheck applyByNode nodeNum arg (#2792)

---

webapp/content/js/dashboard.js
webapp/graphite/dashboard/views.py
webapp/graphite/errors.py
webapp/graphite/util.py
webapp/tests/base.py
webapp/tests/test_dashboard.py

- [ Fix XSS in some dashboards queries (#2785)](https://github.com/graphite-project/graphite-web/pull/2785)

[1.1.x]  Fix XSS in some dashboards queries (#2785)

---

docs/tags.rst

Space is definitely not allowed as [the parser in carbon](https://github.com/graphite-project/carbon/blob/66ebee19ece0e59d6a802d0ff77bead02191b7ab/lib/carbon/protocols.py#L196-L197) does this:
metric, value, timestamp = line.strip().split()
Thus a space in any part of the tags string or metric name would result in it being cut off and the remaining part would be parsed as part of the value.

Tags Docs: fix allowed characters

---

.github/workflows/codeql-analysis.yml
.github/workflows/tests.yml

This PR bumps GitHub workflows to latest versions, thus avoiding deprecation warnings.

Bump GitHub workflows to latest versions

---

Pipfile
Pipfile.lock
requirements.txt
webapp/graphite/events/models.py

Add support for Pipfile so we can leverage dependabot.

Add Pipfile.lock

---

docs/carbon-daemons.rst

Explicitly state and relate rewrite-rules.conf to carbon-aggregator in the same way that relay-rules.conf is only applied to carbon-relay making it clearer as to what evaluates and executes rewrite-rules.conf

Update carbon-daemons.rst - rewrite-rules

---

docs/render_api.rst
docs/tools.rst

Per #2881, fixes some broken external links on https://graphite.readthedocs.io/en/latest/tools.html

Fix dead external links
